export const PDA_ROLE = {
  title:"Principal Data Analyst", slug:"principal-data-analyst",
  department:"Data", reportsto:"Jacob Savos, Director of Data",
  location:"Remote", employment:"Full-Time, W2", comp:"$170,000 - $220,000",
  mission:"Shape the analytics foundation that helps Cartwheel understand and improve how mental health care reaches students. Your work connects data decisions to real outcomes for kids.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:["Jacob Savos — Director of Data (your hiring manager)","1 Analytics Manager","1 Senior Data Analyst","1 Staff Data Engineer","You — senior IC thought partner to Jacob"],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Role fit, values, compensation"},
    {stage:"Hiring Manager",time:"30m",who:"Jacob Savos",focus:"Systems thinking, data modeling, strategic partnership"},
    {stage:"Take-Home Exercise",time:"60-90m",who:"",focus:"SQL proficiency + analytical proposal"},
    {stage:"Case Study Review",time:"60m",who:"Nicholas Franchetti",focus:"Take-home review, data integrity, dashboards"},
    {stage:"Business Acumen",time:"30m",who:"Sam Blumpkin + Sam Bilow",focus:"Structured reasoning, business scenarios"},
    {stage:"Exec Review",time:"30m",who:"Daniel Ilkovich, CTO",focus:"Final alignment"},
  ],
  contacts:["Manager, Talent Acquisition: Caroline Colpini - caroline.colpini@cartwheelcare.org","Coordinator: Avery Henry - avery.henry@cartwheelcare.org"],
  prep:["Bring 1-2 examples of analytics systems you have owned end-to-end","Walk through context, approach, tradeoffs, validation, and impact","Think about how your work scales — we care about foundations, not one-off outputs","This is a conversation, not a performance"],
  thrive:["Think in systems and care about foundations, not just outputs","Take ownership from concept through durable implementation","Want to build something that outlasts your tenure","Care genuinely about student mental health impact"],
  notfor:["Need highly defined requirements before starting","Optimize locally without considering long-term maintainability","See governance and documentation as overhead","Prefer isolated work over cross-team partnership"],
  success:[
    {period:"First 90 Days",desc:"Audit data systems, ship one small improvement, build key relationships, and propose 2-3 architecture priorities."},
    {period:"First 6 Months",desc:"Core analytical models well-designed and trusted. Metrics defined consistently. Self-service analytics enabling Product, Clinical, and Ops teams."},
    {period:"First 12 Months",desc:"Analytics shifted from reactive reporting to proactive enablement. Executive team uses data confidently. Recognized as the Director of Data's key thought partner on strategy."},
  ],
  mustHave:["8+ years in analytics, data, or a related technical role","Advanced SQL proficiency with complex, messy datasets","Experience designing analytical data models and defining metrics at scale","Experience with BigQuery, Snowflake, or Redshift","Systems-thinking mindset","Ownership mentality: concept through durable implementation"],
  niceToHave:["Healthcare, mental health, or EdTech domain experience","Early-stage or high-growth startup experience","Experimentation or causal analysis tools (Python, R)","Analytics engineering tooling (dbt, data governance)"],
  whatYoullDo:[
    {label:"Data Architecture",bullets:["Design and evolve core analytical data models","Establish standards for metrics, transformations, and semantic layers","Define best practices for analytics quality and long-term maintainability","Partner with data engineering and product to ensure foundations scale"]},
    {label:"Technical Leadership",bullets:["Serve as senior thought partner to the Director of Data","Provide architectural guidance across the data team","Set the bar for what great analytics work looks like at Cartwheel","Support evolution from ad-hoc analysis to productized solutions"]},
    {label:"Enablement",bullets:["Build and support self-service analytics and executive-ready reporting","Ensure new launches are instrumented with clear success metrics from Day 1","Improve measurement of outcomes: access to care, conversion, retention","Support experimentation across R&D, Marketing, and Operations"]},
    {label:"Governance",bullets:["Champion data quality through testing, monitoring, and governance","Ensure analytical workflows are reproducible, well-documented, and resilient","Contribute to data dictionaries, metric definitions, and shared documentation"]},
  ],
  aboutRole:"The Principal Data Analyst is a senior individual contributor responsible for shaping the analytics and data foundation at Cartwheel. This role emphasizes data system design, analytical architecture, and defining best practices for how data is modeled and delivered.\n\nYou will work as a staff-level technical leader on the data team — a close thought partner to the Director of Data — helping raise the bar for what good analytical work looks like.",
  compBenefits:"$170,000-$220,000 cash compensation plus competitive equity. Full benefits: PPO medical/vision/dental/orthodontia, paid parental leave (12 weeks), 401K with up to 2% employer match, generous PTO including Dec 25-Jan 1 closure, $500 learning stipend, MacBook, and annual in-person retreat.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:["Research Cartwheel's mission and school-based model","Prepare a concise background summary focused on data leadership","Know your comp expectations within the $170K-$220K range","Think about what draws you to mission-driven work"],questions:["What does success look like in the first 90 days?","How does the data team collaborate with Product and Clinical?","What is the biggest data challenge Cartwheel is working through?"]},
    {stage:"Hiring Manager",prep:["Prepare 1-2 analytics framework examples with full context","Walk through context, approach, tradeoffs, validation, and impact","This is not a deep technical test — clarity of thinking matters most","Think about how you have moved teams from ad-hoc to productized solutions"],questions:["What are the 2-3 most important things to accomplish in year one?","How do you see the analytics team evolving over the next 12-18 months?","What does great thought partnership look like day-to-day?"]},
    {stage:"Take-Home Exercise",prep:["Block 90 uninterrupted minutes — treat it like a real work session","Read all questions before starting so you can manage your time","Write clean SQL with comments to show your thinking","Lead the proposal with the metrics that matter most, and explain your reasoning"],questions:[]},
    {stage:"Case Study Review",prep:["Prepare a tight 3-minute take-home recap: problem, scope, approach","Walk through your SQL — be ready to discuss efficiency and alternatives","Be honest about gaps or assumptions — strong candidates own them","Think through what a Day 1 dashboard for a new service line would look like"],questions:["What does the current data quality monitoring process look like?","How does the team handle discrepancies between data sources?","What does the analytics tooling stack look like end-to-end?"]},
    {stage:"Business Acumen",prep:["Practice walking through a problem out loud — narrate your thinking","Prepare to ask clarifying questions before jumping to answers","Propose next steps and recommendations, not just diagnoses","This is collaborative, not adversarial — think of it as a working session"],questions:["What business problems is the data team most focused on?","How does data inform go-to-market or expansion decisions?","What does the relationship between data and clinical look like?"]},
    {stage:"Exec Review",prep:["Prepare your long-term vision for data at a company like Cartwheel","Have a thoughtful answer for where you want to be in 3 years","Know why Cartwheel specifically — mission alignment will come up","Prepare 2-3 questions that show strategic thinking"],questions:["How does the exec team use data today, and how would you like that to evolve?","What is Cartwheel's biggest strategic bet over the next 2 years?","How does data infrastructure factor into the growth roadmap?"]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:["Research Cartwheel's mission and school-based model","Prepare your background summary","Know your comp expectations","Review the job description"]},
    {stage:"Before HM Interview",items:["Prepare 2 analytics framework examples","Practice walking through tradeoffs out loud","Review Cartwheel's clinical model","Prepare 3-4 thoughtful questions for Jacob"]},
    {stage:"Before Take-Home",items:["Block 90 uninterrupted minutes","Re-read all questions before starting","Prepare a clean memo or slide deck template","Plan to submit within one week"]},
    {stage:"Before Case Study Review",items:["Prepare a 3-min take-home recap","Review your SQL for efficiency improvements","Think through your data integrity approach","Prepare dashboard design thinking"]},
    {stage:"Before Business Acumen",items:["Practice metric decomposition out loud","Prepare to ask clarifying questions","Review Cartwheel's business model","Think about how data enables go-to-market decisions"]},
    {stage:"Before Exec Review",items:["Prepare your long-term vision for data at Cartwheel","Sharpen your why Cartwheel answer","Prepare 2-3 strategic questions for Daniel","Reflect on what excites you most about the mission"]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Manager, Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Hiring Manager",name:"Jacob Savos",title:"Director of Data",href:"https://www.linkedin.com/in/jacob-savos/"},
    {label:"Take-Home Exercise",name:"",title:"",href:null},
    {label:"Case Study Review",name:"Nicholas Franchetti",title:"",href:"https://www.linkedin.com/in/nfranchetti/"},
    {label:"Business Acumen",name:"Sam Blumpkin + Sam Bilow",title:"",href:null,hrefs:["https://www.linkedin.com/in/samblumkin/","https://www.linkedin.com/in/sam-bilow-59434150/"]},
    {label:"Exec Review",name:"Daniel Ilkovich",title:"CTO",href:"https://www.linkedin.com/in/ilkovich/"},
  ],
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const CTRL_ROLE = {
  title:"Controller", slug:"controller",
  department:"Finance", reportsto:"Sam Bilow, VP of Finance",
  location:"Remote", employment:"Full-Time, W2", comp:"Competitive Base Compensation + Equity",
  mission:"Build Cartwheel's accounting function from the ground up — insourcing from an outsourced firm, leading ERP selection and implementation, and navigating the company's first external audit. This is a builder role, not a maintenance role.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:["Sam Bilow — VP of Finance (your hiring manager)","BizOps team (cross-functional partner)","Data team (cross-functional partner)","Executive team (board reporting)","1 Staff Accountant (your first hire)"],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Culture fit, motivation, compensation alignment"},
    {stage:"Hiring Manager Deep Dive",time:"45m",who:"Sam Bilow",focus:"Technical depth, leadership philosophy, strategic thinking"},
    {stage:"Technical Dive",time:"60m",who:"Grace Yao",focus:"ERP implementation, audit prep, technical accounting scenarios"},
    {stage:"Take-Home Case Study",time:"60-90m",who:"",focus:"90-day transition plan, risk assessment, operational prioritization"},
    {stage:"Case Study Review",time:"45m",who:"Sam Bilow + Jeff Sword",focus:"Presentation of case study, Q&A, strategic discussion"},
    {stage:"Exec Review",time:"30m",who:"Dan Tartakovsky, COO",focus:"Values alignment, long-term vision, leadership presence"},
  ],
  contacts:["Manager, Talent Acquisition: Caroline Colpini","Coordinator: Avery Henry"],
  prep:["Bring specific examples of building or scaling accounting functions — not just maintaining them","Be ready to discuss ERP implementations with real detail: what you selected, why, and what broke","This process values strategic thinking as much as technical depth","We care about how you communicate with non-finance partners — show that skill","This is a conversation, not an exam — ask sharp questions back"],
  thrive:["Have a builder mentality and are comfortable creating structure from scratch","Are self-directed and energized by standing up new functions","Can translate finance concepts for non-finance stakeholders","Are comfortable pushing back diplomatically when needed","Thrive in ambiguity and can move work forward without a perfect playbook"],
  notfor:["Prefer highly structured environments with established processes","Need significant direction to operate effectively","Are uncomfortable with ambiguity or evolving priorities","Have a purely tactical or transactional mindset without strategic perspective","Wait for playbooks instead of writing them"],
  success:[
    {period:"First 90 Days",desc:"Completed thorough operational audit of current accounting state. Mapped Formation Financial relationship and developed insourcing sequencing plan. Evaluated ERP options and presented recommendation. Established working relationships with BizOps, Data, RCM, and executive team. Hired Staff Accountant."},
    {period:"First 6 Months",desc:"ERP implementation underway with clear milestones. First phase of accounting insourcing complete. Month-end close process owned and running smoothly. Audit preparation plan in place with documentation standards established. Chart of accounts designed and operational."},
    {period:"First 12 Months",desc:"ERP fully implemented and operational. First external audit completed successfully. Accounting function fully insourced with scalable processes. Financial reporting connected to operational metrics. Function capable of supporting significant growth without quality degradation."},
  ],
  mustHave:["CPA certification (active, pursuing, or inactive acceptable)","Experience leading or playing a primary role in an ERP implementation (selection, design, rollout) and operating in that system afterward","Track record of building or significantly scaling an accounting function or key processes","Experience preparing for and navigating external audits (planning, documentation, remediation, auditor interaction)","Strong GAAP knowledge and comfort with revenue recognition — healthcare experience more critical than SaaS","Experience managing or transitioning from outsourced accounting relationships","Proven ability to partner with Finance leadership, BizOps, Data, and RCM to connect financial reporting to operational reality"],
  niceToHave:["First audit experience (took a company through its first external audit)","Healthcare experience — especially behavioral health, Medicaid fee-for-service, or payer-heavy environments","Experience with multi-state operations","Familiarity with NetSuite, Sage Intacct, or similar mid-market ERPs","Background in a venture-backed environment with board reporting, fundraising, or exit preparation","EdTech or K-12 education experience"],
  whatYoullDo:[
    {label:"Build and Lead the Accounting Function",bullets:["Own core processes including month-end close, reconciliations, controls, and reporting","Design scalable accounting policies and workflows","Lead the transition from outsourced accounting (Formation Financial) to fully in-house","Hire and develop a Staff Accountant as your first team member"]},
    {label:"Lead ERP Selection and Implementation",bullets:["Evaluate and select a modern ERP (NetSuite, Intacct, etc.) with cross-functional partners","Own configuration, chart of accounts design, integrations, and process buildout","Establish a strong, audit-ready financial infrastructure from day one","Manage the 6-12 month implementation timeline across departments"]},
    {label:"Own Technical Accounting and Audit Readiness",bullets:["Lead GAAP-compliant reporting and technical accounting decision-making","Prepare Cartwheel for its first external audit","Manage documentation, controls, and alignment with auditors and internal teams","Navigate revenue recognition complexity across healthcare and SaaS models"]},
    {label:"Partner Across the Business",bullets:["Work with BizOps and Data to connect financial reporting to operational metrics (RCM, state P&L, revenue quality)","Collaborate with RCM and Health Plan Ops on payer dynamics, collections, and revenue integrity","Support leadership with budgeting, forecasting, and board reporting","Translate finance concepts into language that Ops, RCM, BizOps, and Data can act on"]},
  ],
  aboutRole:"We're hiring our first Controller to build a modern, scalable accounting function that will support Cartwheel's rapid growth. As our accounting leader, you'll build core processes from scratch, lead our ERP selection and implementation, and create the financial infrastructure we'll rely on for audits, fundraising, and multi-state expansion.\n\nThis is a true builder role — not inheriting a fully built function, but designing the systems, controls, and processes that will scale with the company. Reporting to our VP of Finance, you'll be a key strategic partner to teams across the company — including BizOps, Data, RCM, and Operations — as we bring high-quality mental health support to students everywhere.",
  compBenefits:"Competitive base compensation plus meaningful equity package. Full benefits: PPO medical/vision/dental/orthodontia, paid parental leave, 401K with up to 2% employer match, unlimited/flexible PTO plus federal holidays, life insurance, $500 annual learning stipend, MacBook, and annual in-person retreat.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:["Research Cartwheel's mission, school-based model, and Series B stage","Prepare a concise summary of your accounting function-building experience","Know your comp expectations around the $200K OTE range","Think about what draws you to a builder role at an early-stage company"],questions:["What does the current accounting setup look like with Formation Financial?","What's the timeline for ERP implementation and the first audit?","What does success look like in the first 90 days?"]},
    {stage:"Hiring Manager Deep Dive",prep:["Prepare specific examples of building or redesigning a chart of accounts and revenue recognition framework","Think through how you would sequence insourcing accounting from an outsourced firm","Be ready to discuss a time revenue recognition was structurally misaligned and how you fixed it","Prepare examples of transitioning work from non-finance teams while maintaining relationships"],questions:["What are the biggest accounting risks you see as Cartwheel scales across states?","How does the BizOps team currently handle finance-adjacent work?","What does the relationship between Finance and RCM look like today?"]},
    {stage:"Technical Dive",prep:["Prepare detailed examples of ERP implementations you have led or been deeply involved in","Be ready for technical accounting scenarios — revenue recognition, multi-state complexity","Think through your approach to monthly close process design and audit readiness","Prepare to discuss systems and process scaling in concrete terms"],questions:["What ERP systems is Cartwheel currently evaluating?","What does the current tech stack look like for billing and revenue operations?","What's the expected timeline and budget for the ERP implementation?"]},
    {stage:"Take-Home Case Study",prep:["Block 60-90 uninterrupted minutes","Read the full prompt before starting — understand the scenario and data provided","Focus on prioritization and sequencing, not trying to solve everything","Tie your plan to specific risks and how you would mitigate them","Think about the human element — the outsourced team, internal stakeholders, your future hire"],questions:[]},
    {stage:"Case Study Review",prep:["Prepare a clear 10-minute walkthrough of your case study response","Anticipate tough questions about your assumptions and trade-offs","Be ready to discuss what you would do differently with more time or information","This is a strategic conversation — show how you think, not just what you wrote"],questions:["What aspects of the transition carry the most risk?","How would you handle pushback from teams during the insourcing process?","What would you prioritize if the audit timeline got accelerated?"]},
    {stage:"Exec Review",prep:["Prepare 3 questions you would need answered before signing on as the first in-seat Controller","Have an example of recommending against the short-term financially optimal choice for ethical or long-term reasons","Think about what you would invest in during the next 12 months that most companies wait too long to build","Dan expects sharp questions — this is a two-way conversation"],questions:["What is Cartwheel's biggest strategic bet over the next 2-3 years?","How does the exec team think about the balance between growth speed and financial infrastructure?","What does the finance function look like in your vision for Cartwheel at 5-10x scale?"]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:["Research Cartwheel's mission and school-based model","Prepare your background summary focused on accounting function building","Know your comp expectations around $200K OTE","Review the role description and think about your builder examples"]},
    {stage:"Before Hiring Manager Deep Dive",items:["Prepare examples of chart of accounts design and revenue recognition work","Think through insourcing sequencing strategy","Prepare a revenue recognition misalignment example with resolution","Prepare 3-4 thoughtful questions for Sam"]},
    {stage:"Before Technical Dive",items:["Prepare detailed ERP implementation examples","Review your technical accounting knowledge — GAAP, ASC 606, healthcare revenue","Think through monthly close process design","Prepare systems scaling examples"]},
    {stage:"Before Take-Home Case Study",items:["Block 60-90 uninterrupted minutes","Read the full prompt before starting","Focus on prioritization and risk mitigation","Think about stakeholder dynamics in the transition"]},
    {stage:"Before Case Study Review",items:["Prepare a clear 10-minute walkthrough","Anticipate questions about assumptions and trade-offs","Think about what you would do differently","Prepare to discuss strategic implications"]},
    {stage:"Before Exec Review",items:["Prepare 3 due diligence questions about Cartwheel","Prepare an example of principled decision-making over short-term optimization","Think about 12-month foundational investments","Prepare 2-3 strategic questions for Dan"]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Manager, Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Hiring Manager Deep Dive",name:"Sam Bilow",title:"VP of Finance",href:"https://www.linkedin.com/in/sam-bilow-59434150"},
    {label:"Technical Dive",name:"Grace Yao",title:"Outsourced Controller",href:"https://www.linkedin.com/in/graceyao-compassion/"},
    {label:"Take-Home Case Study",name:"",title:"",href:null},
    {label:"Case Study Review",name:"",title:"",href:null,multiHrefs:[
      {name:"Sam Bilow",href:"https://www.linkedin.com/in/sam-bilow-59434150"},
      {name:"Jeff Sword",href:"https://www.linkedin.com/in/jeffrey-sword-80070a31/"},
    ]},
    {label:"Exec Review",name:"Dan Tartakovsky",title:"COO",href:"https://www.linkedin.com/in/tartakovsky/"},
  ],
  applyUrl:"https://job-boards.greenhouse.io/cartwheelcare/jobs/4992170007",
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const GROM_ROLE = {
  title:"Government Relations Operations Manager", slug:"government-relations-operations-manager",
  department:"Government Affairs & Partnerships", reportsto:"Jonathan Adler, VP Government Relations",
  location:"Remote (travel required 1–2x per quarter)", employment:"Full-Time, W2", comp:"Competitive Base + Meaningful Equity",
  mission:"Cartwheel is at an inflection point in state expansion strategy. The Government Relations team manages relationships across multiple states, but volume of workstreams has exceeded team capacity. This role builds the operational infrastructure — briefs, trackers, compliance tracking — that lets the GR team scale without losing deals to slow follow-through or administrative gaps.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:[
    "Jonathan Adler — VP Government Relations (your hiring manager)",
    "GR Account Executives — 3–4 people managing state relationships and deals",
    "GR Executives — 2 people overseeing strategy and lobbying direction",
    "Marketing Lead — cross-functional partner for brief content and distribution",
    "Data/Analytics Team — partner for KPI definition and reporting",
    "Thought Leadership — partner for content in briefs and external assets",
  ],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Role fit, values, compensation, mission alignment"},
    {stage:"Hiring Manager Interview",time:"30m",who:"Jonathan Adler",focus:"Strategic thinking, autonomy, startup mindset, mission alignment depth"},
    {stage:"Take-Home Exercise",time:"Self-guided",who:"",focus:"Operational thinking, process design, written communication"},
    {stage:"Functional Deep Dive",time:"30m",who:"Dan Tartakovsky, COO",focus:"Hands-on operational capability, process design, tool proficiency, cross-functional judgment"},
    {stage:"Cross-Functional Collaboration + Partnership",time:"45-60m",who:"Emily Paisner, Head of Marketing + School Success Leader",focus:"Partnership building, communication clarity, receptiveness to feedback"},
    {stage:"Executive Review",time:"30m",who:"Joe English, CEO",focus:"Mission alignment authenticity, judgment, growth mindset"},
  ],
  contacts:["Manager, Talent Acquisition: Caroline Colpini - caroline.colpini@cartwheelcare.org","Recruiter: Avery Henry - avery.henry@cartwheelcare.org"],
  prep:[
    "Research Cartwheel's mission and current state expansion strategy before interviews",
    "Come prepared with 2–3 concrete examples of systems you've built that others use",
    "Think about a time you coordinated across teams without formal authority",
    "Understand why student mental health access matters — beyond the talking points",
    "Be ready to discuss your comfort with ambiguity and autonomous work",
    "Have questions ready about the GR landscape and team structure",
  ],
  thrive:[
    "Find satisfaction building systems behind the scenes — success is when the GR team closes deals and you enabled it",
    "Thrive on breadth, not depth — context-switching across briefs, compliance, trackers, and event planning energizes you",
    "Are startup-minded — comfortable with blank-page problems, building from scratch, documenting as you go",
    "Are genuinely mission-driven — you understand why student mental health access matters and bring that urgency to even administrative work",
  ],
  notfor:[
    "Want to own external relationships — this role supports the field team, it doesn't replace it",
    "Struggle with ambiguity or shifting priorities — legislative calendars move fast and opportunities emerge quickly",
    "Need a team to manage to feel senior — this role has no direct reports at launch",
    "Are strong strategically but light on execution — this role requires both strategic thinking and hands-on building",
    "Need frequent positive feedback to stay engaged — you'll work mostly autonomously with periodic check-ins",
  ],
  success:[
    {period:"First 90 Days",desc:"Met every GR team member and key cross-functional partners. Completed comprehensive audit of existing infrastructure. Produced first round of monthly impact briefs with documented process. Lobbyist contracts and compliance fully mapped across all jurisdictions. Opportunity tracker and event calendar live and actively used by the team."},
    {period:"First 6 Months",desc:"GR Account Executives report that pre-meeting briefings, collateral requests, and tracking are handled without them having to ask. Monthly impact briefs ship on schedule with tiered approach consistently applied. Opportunity tracker is single source of truth; team updates it automatically. Lobbyist budget tracking current within 5 days of each reporting period."},
    {period:"First 12 Months",desc:"Lobbyist performance reviews completed for all active contracts with data-backed recommendations. VP of GR has live KPI dashboard informing state prioritization decisions. No dropped compliance deadlines, no missed briefs, no surprises. GR team can point to tangible wins where operational support was a contributing factor. Role is evolving toward strategic intelligence gathering and scaling operations as the team grows."},
  ],
  mustHave:[
    "5+ years experience in operations, project management, or chief of staff roles (government affairs, healthcare, education, or high-growth startup environment preferred)",
    "Mission aligned — genuinely passionate about expanding access to student mental health services and enthusiastic about building in a startup environment",
    "Strong writer — able to distill quantitative and qualitative information into crisp briefs for a range of external and internal audiences",
    "Eye for design — able to partner with marketing colleagues to develop clear and compelling assets for government audiences (flyers, slide decks)",
    "Exceptionally organized — you create systems, maintain trackers with precision, and never let balls drop; comfortable coordinating 10+ concurrent workstreams with competing deadlines",
    "Cross-functional coordinator — you know how to get buy-in, create clear frameworks, and keep teams aligned, including without formal authority",
    "Technically proficient — fluent in project management tools (Asana, Google Sheets) and CRM systems (Salesforce, Gong); learns new tools quickly",
  ],
  niceToHave:[
    "State government relations or public affairs background",
    "Healthcare or education policy knowledge",
    "Familiarity with lobbying compliance requirements",
    "RFP/procurement process experience",
  ],
  whatYoullDo:[
    {label:"Government Relations Marketing",bullets:[
      "Coordinate with Marketing, Data, Thought Leadership, and other teams to develop monthly marketing impact briefs across active states (personalized and generic depending on state tier)",
      "Manage distribution schedule and delivery of briefs to legislators, governor's staff, agency staff, and community partners",
      "Gather feedback on and continuously improve the brief development process",
      "Develop additional collateral as needed (e.g., two-pagers, slide decks, fliers)",
    ]},
    {label:"Government Relations Team Knowledge Management",bullets:[
      "Maintain centralized opportunity trackers with high accuracy",
      "Maintain GR event trackers (conference calendars, attendee lists, follow-ups)",
      "Maintain library of GR collateral (monthly briefs, two-pagers, talking points)",
      "Maintain library of GR team onboarding and training materials",
    ]},
    {label:"Government Relations Team Enablement",bullets:[
      "Support field team members to maximize their effectiveness (prepare briefings, direct to appropriate collateral, maintain attendee lists, track follow-ups)",
      "Plan and execute major GR team events including state events and road shows",
      "Ensure all team members have access to up-to-date materials and intelligence",
      "Note: This role is not expected to represent Cartwheel in the field on a regular basis, though may involve staffing some in-person events",
    ]},
    {label:"Contract Lobbying Operations",bullets:[
      "Track spend and outcomes for lobbyists in coordination with GR Executives",
      "Support development of lobbyist ROI analyses and performance reviews",
      "Develop standardized lobbyist onboarding materials and information sessions",
      "Manage contracting, compliance, registrations, budget tracking, and ethical standards across all jurisdictions",
      "Note: GR Account Executives own day-to-day lobbyist management and strategy; this role provides enablement",
    ]},
    {label:"Research & Strategic Support",bullets:[
      "Conduct research and produce regular intelligence briefings covering notable developments across states, including emerging funding sources",
      "Track KPIs across government activities (e.g., pipeline value, conversion rates)",
      "Provide recommendations to VP of GR on state opportunity prioritization",
    ]},
  ],
  aboutRole:"As a Government Relations Operations Manager, you'll be the operational backbone of Cartwheel's government relations team — the person who makes sure our GR strategy translates into impact at scale.\n\nYou'll manage the systems, workflows, and intelligence that enable our GR executives and state-based team to influence education policy and secure funding for student mental health. This is a high-leverage operations role: you won't be in the room for every negotiation, but you'll ensure everyone in the room has what they need to succeed.\n\nYou'll own the end-to-end operations of our government affairs function across 10+ states, from tracking legislative opportunities and coordinating lobbyist partnerships to producing monthly impact briefs that shape how policymakers think about student mental health.",
  compBenefits:"Competitive compensation at market rate for a mid-level operations role in a startup environment. Benefits include competitive health insurance, equity package, 401K with up to 2% employer match, unlimited PTO, $500 annual professional development budget, remote-first with travel required 1–2x per quarter. Target start date: March 27, 2026.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:[
      "Research Cartwheel's mission and school-based mental health model",
      "Prepare a concise background summary focused on operational and coordination experience",
      "Know your compensation expectations",
      "Think about what draws you to a mission-driven operations role",
    ],questions:[
      "What does the current GR operational infrastructure look like?",
      "How many active states is Cartwheel in today vs. the 12-month target?",
      "What does success look like in the first 90 days?",
    ]},
    {stage:"Hiring Manager Interview",prep:[
      "Prepare 2–3 examples of systems you built that others now rely on",
      "Think about times you operated autonomously without close oversight",
      "Be ready to articulate why you're drawn to mission-driven work specifically",
      "Prepare questions about the GR team structure and current gaps",
    ],questions:[
      "What are the biggest operational gaps the GR team is experiencing right now?",
      "How does the team currently manage pipeline and lobbyist relationships?",
      "What does the biggest win look like in the first 6 months?",
    ]},
    {stage:"Take-Home Exercise",prep:[
      "Block focused, uninterrupted time — treat it like a real work session",
      "Read the full prompt before starting so you can manage your time",
      "Show your thinking and structure, not just your conclusions",
      "Be honest about assumptions and what you'd do with more information",
    ],questions:[]},
    {stage:"Functional Deep Dive",prep:[
      "Prepare specific examples of process design — show the before and after",
      "Be ready to walk through your project management tool experience in detail",
      "Think about how you've handled compliance or deadline-tracking in past roles",
      "Bring a concrete example of a system you built from scratch",
      "Dan is operationally fluent — bring depth, not surface-level answers",
    ],questions:[
      "What tools does the GR team currently use for tracking and communication?",
      "Are there existing lobbyist contracts and compliance frameworks to inherit?",
      "How does Cartwheel think about scaling operations as you enter new states?",
    ]},
    {stage:"Cross-Functional Collaboration + Partnership",prep:[
      "Prepare an example of coordinating a project across teams without direct authority",
      "Think about how you've given and received feedback that changed your approach",
      "Show genuine curiosity about how Marketing and School Success currently work",
      "Be ready to discuss how you build trust quickly with new colleagues",
    ],questions:[
      "How do Marketing and GR currently collaborate on briefs and external content?",
      "What does the School Success team need most from a GR ops partner?",
      "How does the team handle competing priorities across states and functions?",
    ]},
    {stage:"Executive Review",prep:[
      "Prepare your perspective on why operational infrastructure matters at this stage of growth",
      "Have a clear, genuine answer for why Cartwheel specifically resonates with you",
      "Think about where you want to grow in the next 2–3 years",
      "Prepare 2–3 strategic questions about Cartwheel's mission and expansion roadmap",
    ],questions:[
      "What is Cartwheel's state expansion strategy over the next 2 years?",
      "How does the executive team think about the relationship between GR operations and deal velocity?",
      "What does success for this role look like from a leadership perspective?",
    ]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:[
      "Research Cartwheel's mission and school-based model",
      "Prepare your background summary focused on operations and coordination",
      "Know your compensation expectations",
      "Review the job description and think about your builder examples",
    ]},
    {stage:"Before Hiring Manager Interview",items:[
      "Prepare 2–3 system-building examples with clear before/after impact",
      "Think through your experience with autonomous, ambiguous work",
      "Prepare questions about the GR team structure and current infrastructure",
      "Reflect on your personal connection to the mission",
    ]},
    {stage:"Before Take-Home Exercise",items:[
      "Block uninterrupted time before starting",
      "Read the full prompt before writing anything",
      "Structure your response clearly — show your thinking, not just conclusions",
      "Submit within the requested timeframe",
    ]},
    {stage:"Before Functional Deep Dive",items:[
      "Prepare detailed process design examples with before/after context",
      "Review your project management and tool proficiency examples",
      "Think through compliance and deadline-tracking experience",
      "Prepare 2–3 questions for Dan about operational priorities",
    ]},
    {stage:"Before Cross-Functional Collaboration + Partnership",items:[
      "Prepare a cross-functional coordination example without direct authority",
      "Think about how you approach feedback and adjust based on others' input",
      "Review what you know about Cartwheel's Marketing and School Success teams",
      "Prepare thoughtful questions for Emily and the School Success Leader",
    ]},
    {stage:"Before Executive Review",items:[
      "Prepare your perspective on scaling operations at a high-growth company",
      "Sharpen your why Cartwheel answer — make it specific and genuine",
      "Prepare 2–3 strategic questions about mission and state expansion",
      "Reflect on your long-term growth goals",
    ]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Manager, Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Hiring Manager Interview",name:"Jonathan Adler",title:"VP Government Relations",href:"https://www.linkedin.com/in/jonathaneadler/"},
    {label:"Take-Home Exercise",name:"",title:"",href:null},
    {label:"Functional Deep Dive",name:"Dan Tartakovsky",title:"COO",href:"https://www.linkedin.com/in/tartakovsky/"},
    {label:"Cross-Functional Collaboration + Partnership",name:"Emily Paisner",title:"Head of Marketing",href:"https://www.linkedin.com/in/emilypaisner/",multiHrefs:[
      {name:"Emily Paisner",href:"https://www.linkedin.com/in/emilypaisner/"},
      {name:"School Success Leader",href:null},
    ]},
    {label:"Executive Review",name:"Joe English",title:"CEO",href:"https://www.linkedin.com/in/joe-m-english/"},
  ],
  applyUrl:"https://job-boards.greenhouse.io/cartwheelcare/jobs/5070368007",
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const FPAA_ROLE = {
  title:"Finance Associate", slug:"fpa-associate",
  department:"Finance", reportsto:"Sam Bilow, VP Finance",
  location:"Remote", employment:"Full-Time, W2", comp:"$90,000–$140,000 + meaningful equity",
  roadmapNote:"Our interview process is designed to reflect the real work of this role — each conversation evaluates a different dimension of how you think, prioritize, and lead, especially in a fast-moving, mission-driven environment like ours.\n\nThe roadmap below outlines the full arc of the process. Not every candidate moves through every stage, and the order can shift — progression is based on mutual fit and alignment as we get to know each other.",
  mission:"We're hiring a Finance Associate to own financial reporting, planning, and KPI/OKR visibility across Cartwheel — building the financial infrastructure that helps a fast-growing mental health company make smarter, faster decisions. This is a net-new role on a mission-driven team, with real scope and real impact from day one.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:[
    "Sam Bilow — VP Finance (your hiring manager)",
    "April Liu — Healthcare Business Operations & Strategy",
    "Daniel Tartakovsky — COO & Co-Founder",
  ],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Role fit, values, compensation alignment"},
    {stage:"Hiring Manager Screen",time:"45m",who:"Sam Bilow",focus:"Finance background, relevant experience, motivation for Cartwheel"},
    {stage:"Take-Home Exercise",time:"Self-guided",who:"",focus:"Financial modeling, analytical thinking, written communication"},
    {stage:"Cross-Functional Panel",time:"60m",who:"April Liu",focus:"Operational partnership, cross-functional collaboration, stakeholder communication"},
    {stage:"Executive Interview",time:"30m",who:"Daniel Tartakovsky",focus:"Strategic fit, company values, leadership presence"},
  ],
  contacts:["Manager, Talent Acquisition: Caroline Colpini - caroline.colpini@cartwheelcare.org","Coordinator: Avery Henry - avery.henry@cartwheelcare.org"],
  prep:[
    "Cartwheel is early-stage and scrappy — show that you're comfortable with ambiguity and excited about building",
    "The mission matters here — come ready to speak authentically about why you care about student mental health",
    "Be concrete: specifics about your models, your impact, your process are more compelling than general claims",
    "Candidates who do well at Cartwheel tend to be collaborative, low-ego, and self-directed",
  ],
  thrive:[
    "Love turning messy data into clear decisions — and know how to communicate findings to a non-finance audience",
    "Are energized by building infrastructure from scratch, not just maintaining what exists",
    "Want your work to matter — you understand that better financial visibility means better outcomes for kids",
    "Are comfortable moving fast with limited resources and a lot of ambiguity",
    "Take pride in the quality and accuracy of your models and reports",
  ],
  notfor:[
    "Prefer highly structured, well-defined roles with minimal ambiguity",
    "Are looking for a large finance team with narrow specialization",
    "Want a role where someone else drives the agenda and prioritization",
    "Are not excited by the mission of supporting student mental health",
  ],
  success:[
    {period:"First 90 Days",desc:"Oriented across Cartwheel's financial systems, models, and reporting cadences. Introduced yourself to key department leaders and understand their budgets and KPIs. Taken over ownership of the monthly financial reporting cycle and made at least one meaningful improvement to how it runs."},
    {period:"First 6 Months",desc:"Rebuilt or significantly improved Cartwheel's core KPI dashboards, partnered with at least two department heads on budget-vs-actual analysis, and produced your first forward-looking forecast used in a board or investor context. Leaders across the org know you as a trusted, proactive financial partner."},
    {period:"First 12 Months",desc:"Running the annual budgeting cycle end-to-end with systems that make financial reporting faster, more automated, and more decision-useful. Delivered at least one major ad-hoc analysis that directly influenced a strategic decision. A key voice in how Cartwheel thinks about runway, resource allocation, and financial health."},
  ],
  mustHave:[
    "2–4 years of experience from investment banking, management consulting (MBB, Big 4, or similar), or a high-rigor FP&A role — startup or high-growth experience is a strong plus",
    "Fluency in Excel — VLOOKUP, pivot tables, scenario modeling, and building clean, well-structured financial models from scratch",
    "Ability to translate financial concepts clearly for non-financial audiences — you know when to simplify and when precision matters; can build a clean board slide or exec summary from scratch",
    "Self-directed and ownership-oriented: spots problems, proposes solutions, doesn't wait to be asked",
    "Comfortable operating with incomplete data — can forecast with 80% information and refine from there",
    "Care about the mission — understands that finance is in service of student mental health, not the other way around",
  ],
  niceToHave:[
    "Exposure to healthcare, EdTech, or high-growth startups",
    "Experience with financial reporting tools (e.g., Looker, Tableau, or similar BI tools)",
    "Prior experience supporting board or investor reporting",
    "Familiarity with KPI/OKR frameworks",
  ],
  whatYoullDo:[
    {label:"Strategic Finance",bullets:[
      "Build forward-looking forecasts to support runway planning and board communication",
      "Identify opportunities to automate and scale financial reporting processes",
      "Conduct ad-hoc analyses that help leadership make faster, better-informed decisions",
    ]},
    {label:"Financial Modeling & Reporting",bullets:[
      "Maintain and improve Cartwheel's core financial model — P&L, cash burn, scenario modeling",
      "Own monthly board slide deck, investor reporting, and SLT financial updates",
      "Maintain and continuously improve KPI dashboards",
    ]},
    {label:"Budgeting & Planning",bullets:[
      "Lead the annual budgeting cycle: templates, department kick-offs, reviews, and final consolidation",
      "Partner with department heads on budget planning and resource allocation",
      "Maintain budget vs. actual tracking and variance analysis",
    ]},
  ],
  aboutRole:"We're hiring a Finance Associate to own financial reporting, planning, and KPI/OKR visibility across the organization. This is a net-new role — and a real opportunity to build something. Right now, our financial and operational metrics live in different systems, most reporting is backward-looking, and department leaders don't yet have the structured financial partnership they need to make confident decisions.\n\nReporting to Sam Bilow, VP Finance, you'll consolidate our reporting infrastructure, build forward-looking forecasts, and become a trusted cross-functional partner to leaders across Care Ops, Clinical, Product, Engineering, and beyond. If you thrive in high-rigor, fast-paced environments — think Investment Banking or Big 4 Consulting — and want to apply that edge to growing a company with a mission that matters, this role is for you.",
  compBenefits:"$90,000–$140,000 in base salary plus a meaningful equity ownership stake in Cartwheel. Benefits include generous PPO medical, vision, and dental/ortho coverage, life insurance, generous paid time off including company closure from Christmas–New Year's (12/25–1/1), paid holidays and sick leave, paid parental leave, 401K with up to 2% employer match, an annual learning stipend, and a laptop. Fully remote with regular in-person retreats.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:[
      "Review Cartwheel's website and be ready to speak to why the mission resonates with you personally",
      "Come prepared to discuss your compensation expectations — we share the full range upfront",
      "Think through your 2–3 most relevant experiences in FP&A, finance, or a related field",
    ],questions:[
      "What's the biggest financial challenge Cartwheel is trying to solve right now?",
      "What does the interview process look like after this stage?",
    ]},
    {stage:"Hiring Manager Screen",prep:[
      "Be ready to walk through a financial model or reporting workflow you've built end-to-end",
      "Think about a time you had to translate complex financial data for a non-finance stakeholder",
      "Prepare to speak to how you prioritize when you have multiple competing requests",
    ],questions:[
      "What's the current state of financial reporting at Cartwheel, and where do you most want this role to have impact first?",
      "What does the relationship between Finance and other departments look like today vs. where you want it to go?",
    ]},
    {stage:"Take-Home Exercise",prep:[
      "Block focused, uninterrupted time — treat it like a real work session",
      "Read the full prompt carefully before starting",
      "Show your thinking and structure, not just your conclusions",
      "Be honest about assumptions and what you'd do with more information",
    ],questions:[]},
    {stage:"Cross-Functional Panel",prep:[
      "April Liu comes from a healthcare business operations background — think about how you'd partner cross-functionally, not just report numbers",
      "Be ready to share how you've managed competing asks from different department heads",
      "Come with examples of times you built trust with a non-finance partner",
    ],questions:[
      "What does a great finance partner look like from your perspective?",
      "Where do you feel like you most need better financial visibility to do your job well?",
    ]},
    {stage:"Executive Interview",prep:[
      "Daniel Tartakovsky is the COO and Co-Founder — he'll be assessing strategic thinking and cultural fit",
      "Be ready to talk about why you want to join a company at this stage of growth",
      "Have a thoughtful point of view on what makes a company's financial infrastructure a competitive advantage",
    ],questions:[
      "How does leadership think about the relationship between financial discipline and mission-driven growth?",
      "What's the most important thing you'd want someone in this role to accomplish in their first year?",
    ]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:[
      "Read cartwheel.org and skim the Wall of Love",
      "Research student mental health landscape — why schools are a lever point",
      "Prepare a 2-minute 'who I am and why I'm interested' answer",
      "Have your compensation expectations ready to share",
    ]},
    {stage:"Before Hiring Manager Screen",items:[
      "Have 2–3 work samples or model examples in mind (ready to describe, not necessarily share)",
      "Review Cartwheel's publicly available data (partnerships, growth, funding)",
      "Prepare questions about the current state of financial infrastructure",
    ]},
    {stage:"Before Take-Home Exercise",items:[
      "Block uninterrupted time before starting",
      "Read the full prompt before writing anything",
      "Structure your work clearly — show your thinking, not just conclusions",
      "Submit within the requested timeframe",
    ]},
    {stage:"Before Cross-Functional Panel",items:[
      "Review April Liu's LinkedIn to understand her background and scope",
      "Think about how Finance and Ops can work as partners, not separately",
      "Prepare a story about navigating a disagreement or tension with a non-finance stakeholder",
    ]},
    {stage:"Before Executive Interview",items:[
      "Review Daniel Tartakovsky's LinkedIn and any published interviews or posts",
      "Be ready to articulate your personal connection to the mission",
      "Prepare a thoughtful question about company strategy or financial priorities",
    ]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Manager, Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Hiring Manager Screen",name:"Sam Bilow",title:"VP Finance",href:"https://www.linkedin.com/in/sam-bilow-59434150/"},
    {label:"Take-Home Exercise",name:"",title:"",href:null},
    {label:"Cross-Functional Panel",name:"April Liu",title:"Healthcare Business Operations & Strategy",href:"https://www.linkedin.com/in/april-liu-2020a/"},
    {label:"Executive Interview",name:"Daniel Tartakovsky",title:"COO & Co-Founder",href:"https://www.linkedin.com/in/tartakovsky/"},
  ],
  applyUrl:"https://job-boards.greenhouse.io/cartwheelcare/jobs/5073358007",
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const ROA_ROLE = {
  title:"Revenue Operations Analyst", slug:"revenue-operations-analyst",
  department:"Revenue Operations", reportsto:"Jeff Sword, Director of Revenue Operations",
  location:"Remote", employment:"Full-Time, W2", comp:"$75,000 – $90,000 + meaningful equity",
  mission:"The Revenue Operations Analyst owns the tactical execution layer that keeps Cartwheel's deals moving, districts going live, and GTM teams working from clean, reliable data — so the business can scale from 300 to 1,000+ school districts without operational drag.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:[
    "Jeff Sword — Director of Revenue Operations (your manager and primary day-to-day partner)",
    "Sales Team (AEs and Sales Leadership) — primary internal customers for deal desk and CRM support",
    "Customer Success Team — provisioning and renewal support",
    "Finance / AR Team — invoice coordination and financial close",
    "Marketing Operations Administrator — peer collaboration on lead-to-opportunity handoffs",
  ],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Avery Henry",focus:"Role fit, Salesforce proficiency, remote self-management, comfort with tactical execution work"},
    {stage:"Hiring Manager Screen",time:"45m",who:"Jeff Sword",focus:"Deal desk process ownership, CRM data integrity, judgment on edge cases"},
    {stage:"Take-Home Exercise",time:"Self-guided",who:"",focus:"Operational workflow, Salesforce judgment, written communication"},
    {stage:"Functional Panel",time:"60m",who:"Jeff Sword, Andi Kwon, Suzy Hall",focus:"Cross-functional collaboration, stakeholder responsiveness, documentation discipline"},
  ],
  contacts:["Recruiter + Coordinator: Avery Henry - avery.henry@cartwheelcare.org","Manager, Talent Acquisition: Caroline Colpini - caroline.colpini@cartwheelcare.org"],
  prep:[
    "Every stage probes for specificity — 'we did X' won't land here; know what YOU owned and what YOU did",
    "This role is execution-heavy by design; if that energizes you, show it with examples — don't just say you're comfortable with operational work",
    "Interviewers are evaluating whether you'd be reliable under volume pressure, not just capable on a good day",
    "Cartwheel serves 1.5M students across 350+ school districts — connecting your work to that mission will resonate authentically with this team",
    "Be honest about what you know and what you'd need to learn; the team values self-awareness about ramp over overconfidence",
  ],
  thrive:[
    "Take ownership without needing constant direction — you manage your own queue and communicate proactively",
    "Find genuine satisfaction in accuracy, task completion, and a clean CRM record",
    "Are comfortable with high-volume, fast-paced work during peak periods (Q4/Q1 sales close)",
    "Pick up new tools and processes quickly and document as you go",
    "Update stakeholders before they have to ask",
  ],
  notfor:[
    "Need heavily structured processes already in place before you can operate independently",
    "Prefer creative or strategic work over execution and repeatable operational tasks",
    "Need frequent in-person interaction or structured daily oversight to stay productive",
    "Are uncomfortable being 'in the weeds' with tactical work for sustained periods",
    "See this role as a transitional stepping stone to something more strategic",
  ],
  success:[
    {period:"First 90 Days",desc:"Completed business model onboarding (3+ customer calls listened to), built working knowledge of the full revenue tech stack (Salesforce, Gong, Outreach, Adobe Sign, DocuSign, Guru), and can execute the end-to-end opportunity closing workflow — validation, invoicing, COI requests, portal provisioning, vendor registration — with Director oversight. Understand the business model well enough to catch errors before they ship."},
    {period:"First 6 Months",desc:"Independently handle 80% of Tier 1 deal desk and provisioning requests without escalation. Close opportunities from Closing stage to fully invoiced and provisioned within a 24-hour turnaround. Proactively reduced Lead and Opportunity records scoring below 75% health threshold by 50% through ongoing hygiene monitoring — not one-time cleanup."},
    {period:"First 12 Months",desc:"Own 90% of the tactical RevOps workload, escalating only items requiring senior judgment or notarization. Built comprehensive Guru documentation for opportunity closing workflows and all partnership invoicing processes. The primary RevOps point of contact for GTM teams — Jeff can take a week off and deal desk doesn't stop."},
  ],
  mustHave:[
    "Hands-on Salesforce proficiency — record navigation, report building, object relationships, and data issue identification (not just general familiarity)",
    "Ability to execute multi-step operational workflows (10+ steps) accurately and consistently under high-volume conditions without shortcuts",
    "Strong written communication with internal stakeholders and external vendors and district procurement contacts",
    "Remote self-management — own your queue, prioritize independently, communicate proactively without being prompted",
    "Google Sheets competency — data manipulation, VLOOKUP-level analysis, clean formatting for reporting",
  ],
  niceToHave:[
    "Salesforce Certified Administrator credential",
    "Prior experience in K–12 ed-tech or public sector procurement cycles",
    "Familiarity with Gong, Outreach, Adobe Sign, or DocuSign (all trainable on Cartwheel's stack)",
    "Experience in a dual Salesforce instance environment",
    "Exposure to ESA or partnership invoicing models",
  ],
  whatYoullDo:[
    {label:"Deal Desk & Provisioning",bullets:[
      "Own end-to-end opportunity closing workflow — validation, contract generation, invoicing, COI requests, portal provisioning, and vendor registration — within a 24-hour SLA",
      "Serve as the primary RevOps point of contact for Sales and Customer Success on deal desk requests, provisioning status, and tool support",
      "Coordinate across Finance/AR and external vendors on invoice workflows, ESA fee schedules, and payment processing",
    ]},
    {label:"CRM Operations",bullets:[
      "Maintain Lead and Opportunity record quality in Salesforce above 75% health thresholds through proactive monitoring — not reactive cleanup",
      "Build reports and dashboards that give GTM teams reliable, current pipeline data",
      "Manage CRM hygiene across Cartwheel's Salesforce environment as the business scales",
    ]},
    {label:"Documentation & Process Building",bullets:[
      "Build and maintain Guru documentation for every repeatable RevOps workflow — opportunity closing, contract generation, partnership invoicing, ESA fee schedules",
      "Ensure no critical process is single-threaded through institutional knowledge",
      "Proactively identify workflow gaps and document before they become errors",
    ]},
  ],
  aboutRole:"Cartwheel is the largest mental health telehealth provider for K–12 schools in the U.S., serving 350+ school districts and 1.5M students. We're scaling fast — from 300 districts to 1,000+ — and the operational infrastructure to support that growth is being built right now.\n\nThe Revenue Operations Analyst is at the center of that infrastructure. This role owns the execution layer that makes every new school district go live: deal desk processing, CRM data integrity, customer provisioning, invoice coordination, and front-line RevOps support for a 20+ person Sales and Customer Success org.\n\nThis isn't a role for someone who wants to dabble in RevOps. It's for someone who takes genuine ownership of operational excellence — who finds satisfaction in a clean Salesforce record, a same-day deal closed, and a workflow documented before anyone had to ask. If that sounds like you, we'd like to meet you.",
  compBenefits:"Base salary $75,000–$90,000 with no variable comp. Cartwheel offers a competitive benefits package including medical, dental, and vision coverage, 401K with up to 2% employer match, generous PTO, remote flexibility, and direct impact on the mental health infrastructure serving 1.5M students across 350+ school districts. As a Series B+ company backed by Menlo Ventures, Reach Capital, and General Catalyst, you'll be joining a high-growth team at a genuinely consequential inflection point.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:[
      "Know your Salesforce experience at a task level — be ready to describe exactly what you've done in Salesforce, not just that you've used it (reports, record types, object relationships, data hygiene)",
      "Be ready with a concrete example of owning a repeatable process end-to-end, with minimal direction, and what that looked like operationally at peak volume",
      "Be honest about your career motivations — this role is genuinely ~80% tactical and repeatable; if that energizes you, explain why with a real example from your history",
      "Think through how you manage your queue when multiple urgent requests hit at the same time in a remote environment",
    ],questions:[
      "What does a typical high-volume week look like for this role right now?",
      "What are the most common Tier 1 requests from Sales and CS?",
      "What does the ramp timeline look like for someone coming in with strong Salesforce fundamentals?",
    ]},
    {stage:"Hiring Manager Screen",prep:[
      "Prepare a specific closing workflow or deal desk process you've owned — know the steps, your role at each one, and exactly what happened when something broke",
      "Think about a time you caught a CRM data issue proactively — not when someone reported it — and what you did about it beyond fixing the record",
      "Be ready to talk about operating in an environment where the playbook wasn't written yet — how did you learn, and what documentation did you leave behind?",
      "Jeff will probe your escalation threshold — know what you'd own independently versus surface, and why, with specific examples",
    ],questions:[
      "What does the current deal desk workflow look like end-to-end, and where are the biggest friction points?",
      "What's the Salesforce environment like today — dual instance, complexity level, admin support structure?",
      "At 12 months, what does it look like if this hire has gone really well?",
    ]},
    {stage:"Take-Home Exercise",prep:[
      "Block focused, uninterrupted time — treat it like a real work session",
      "Read the full prompt carefully before starting so you can manage your time and scope",
      "Be specific about Salesforce actions — not 'I'd look at the records' but what you'd actually do and why",
      "Show your prioritization logic clearly — which issues are highest urgency and what's your reasoning",
      "Be honest about what you'd escalate versus handle independently; the exercise is evaluating how you think, not whether you have all the answers",
    ],questions:[]},
    {stage:"Functional Panel",prep:[
      "This panel includes Jeff (your HM), Andi Kwon (Marketing Operations), and Suzy Hall (Customer Success Enablement) — think about how you've served diverse internal customers before, not just completed tasks",
      "Prepare a story about competing priorities: a same-day request landing while you were mid-task on something else, and how you communicated proactively with both parties",
      "Have a concrete documentation example ready — something you built from scratch; know who it was for, how you built it, and how you verified it was usable",
      "Think through how RevOps supports both Marketing and CS workflows — Andi and Suzy will be evaluating whether you'd be a reliable partner to their teams",
    ],questions:[
      "What do Marketing Ops and CS typically need most from RevOps on a day-to-day basis?",
      "What does the current documentation setup look like — what's in Guru, what's still in people's heads?",
      "How does the team currently handle queue overflow during Q4 close?",
    ]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:[
      "Review Cartwheel's website and understand the core product — mental health telehealth for K–12 schools",
      "Prepare your Salesforce experience summary: specific tasks you've performed, not just platforms listed on your resume",
      "Think through a concrete example of owning a repeatable process end-to-end with limited oversight",
      "Know your compensation expectations, availability, and target start date",
    ]},
    {stage:"Before Hiring Manager Screen",items:[
      "Research Jeff Sword on LinkedIn — understand his background and how he describes the RevOps function",
      "Prepare 2–3 specific stories: closing workflow you owned, CRM issue you caught proactively, undocumented environment you've navigated",
      "Review what you know about deal desk processes — opportunity validation, contract generation, invoicing, provisioning steps",
      "Prepare thoughtful questions about the current state of the RevOps function and where it's heading",
    ]},
    {stage:"Before Take-Home Exercise",items:[
      "Block uninterrupted time before starting — treat it like a real work session",
      "Read the full prompt before writing anything",
      "Show your prioritization logic and Salesforce thinking clearly — not just conclusions",
      "Submit within the requested timeframe",
    ]},
    {stage:"Before Functional Panel",items:[
      "Research Andi Kwon (Marketing Operations) and Suzy Hall (Customer Success Enablement) on LinkedIn",
      "Prepare stakeholder communication stories — competing priorities, proactive communication under pressure",
      "Have your documentation example ready: what you built, who it was for, how you tested it was usable",
      "Think about how RevOps supports Marketing and CS workflows specifically — not just Sales",
    ]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Avery Henry",title:"Talent Acquisition",href:"https://www.linkedin.com/in/averyhenry/"},
    {label:"Hiring Manager Screen",name:"Jeff Sword",title:"Director of Revenue Operations",href:"https://www.linkedin.com/in/jeffrey-sword-80070a31/"},
    {label:"Take-Home Exercise",name:"",title:"",href:null},
    {label:"Functional Panel",name:"",title:"",href:null,multiHrefs:[
      {name:"Jeff Sword",href:"https://www.linkedin.com/in/jeffrey-sword-80070a31/"},
      {name:"Andi Kwon",href:"https://www.linkedin.com/in/andikwon/"},
      {name:"Suzy Hall",href:"https://www.linkedin.com/in/suzy-hall-a8b846101/"},
    ]},
  ],
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const CSM_ROLE = {
  title:"Customer Success Manager", slug:"customer-success-manager-southeast",
  department:"School Success", reportsto:"Jeanine Avjean, Sr. Manager of Customer Success", reportstoHref:"https://linkedin.com/in/jeanine-avjean-1200a01a3/",
  location:"Remote — East Coast preferred; EST/CST hours required; ability to travel to Georgia required", employment:"Full-Time, W2", comp:"$95,000–$110,000 + 10% variable compensation",
  mission:"Cartwheel's Customer Success Managers are the single human thread connecting our clinical model to district outcomes. This role owns a multi-state book of 40–60 school districts — building trusted relationships with district leadership, connecting Cartwheel's utilization data to each district's published strategic plan, and driving the renewals and expansions that fund our mission.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"1,000+",label:"Districts by 2026",sub:"Scaling fast"},{n:"40%",label:"Forecasted Visit Growth",sub:"Year over year"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:[
    "Jeanine Avjean — Sr. Manager of Customer Success (your hiring manager)",
    "Sarah Shoff — VP of School Success (department lead)",
    "6 CSMs across the team (mixed clinical and non-clinical backgrounds)",
    "Key partners: Account Managers, Care Managers/Coordinators, Sales, Product",
  ],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Avery Henry",focus:"Role fit, K-12 context, mission alignment, logistics"},
    {stage:"Hiring Manager Interview",time:"45–60m",who:"Jeanine Avjean",focus:"Revenue ownership, account health instincts"},
    {stage:"Functional Deep Dive",time:"60m",who:"Customer Success Manager, Emily Boyce",focus:"Strategic data narrative, cross-functional navigation"},
    {stage:"Domain & Stakeholder Screen",time:"60m",who:"Suzy Hall",focus:"District leadership navigation, startup fit, clinical boundary clarity"},
    {stage:"Case Study Presentation",time:"60–90m",who:"Jeanine Avjean, Sarah Shoff",focus:"Take-home debrief, strategic communication, executive calibration"},
  ],
  contacts:["Manager, Corporate Talent Acquisition: Caroline Colpini - caroline.colpini@cartwheelcare.org","Recruiter: Avery Henry - avery.henry@cartwheelcare.org","Take-home exercise questions: Avery Henry - avery.henry@cartwheelcare.org"],
  prep:[
    "Every stage probes for specificity — 'we worked with districts to improve utilization' won't land; know what YOU owned, what YOU did, and what changed as a result",
    "This role is genuinely high-touch and relationship-first by design; if that energizes you, show it with examples — don't just say you're comfortable with it",
    "Interviewers are evaluating whether you'd be reliable and proactive under a full book, not just capable with one great district",
    "Cartwheel serves 1.5M students across 350+ school districts — connecting your work to what that means for families and kids will resonate authentically with this team",
    "Be honest about what you know and what you'd need to learn; the team values self-awareness about ramp over overconfidence",
  ],
  thrive:[
    "Are energized by building real relationships with district leadership — not just hitting touchpoints",
    "Naturally tie your work to outcomes, not activity (utilization trends, renewal health, strategic plan alignment)",
    "Are comfortable in a startup environment: some ambiguity, high agility required, processes still being built",
    "Instinctively structure complex situations into clear, manageable components",
    "See clinical nuance — if you have it — as a tool to deploy thoughtfully, not a reason to own the clinical function",
    "Are excited by Cartwheel's mission to serve students in communities that are often overlooked",
  ],
  notfor:[
    "Are coming from a 300+ account, primarily reactive CS model and haven't unlearned the scaled mindset",
    "Require heavy infrastructure, polished playbooks, and defined processes before executing",
    "Expect clean handoffs and fully built workflows (Cartwheel's CS motion is still being shaped)",
    "Want to be the clinical lead in the room rather than a strategic partner who happens to have clinical knowledge",
  ],
  success:[
    {period:"First 90 Days",desc:"Fully onboarded to your book of business. Completed intro calls with all district contacts. Reviewed each district's strategic plan and can map Cartwheel's impact to it. Established a proactive communication cadence. Built strong working relationships with your CSM Manager, Account Managers, and Care Managers."},
    {period:"First 6 Months",desc:"Utilization is trending positively across owned accounts. You're independently connecting Cartwheel data to district strategic goals in QBRs. Providing structured district health updates to leadership. Picking up expansion accounts in new states as we grow. Product feedback loop is active and consistent."},
    {period:"First 12 Months",desc:"Owns 40–60 accounts independently — renewals and expansions pipeline is healthy with no surprises. Trusted advisor status with district leadership across your territory. Operating as a proactive thought partner on care model, not just account owner. Actively contributing to team culture and helping shape what great CS looks like at Cartwheel."},
  ],
  mustHave:[
    "5+ years of Customer Success experience in education, edtech, or school-based mental health",
    "2+ years working in or adjacent to K-12 school systems — can speak district language without translation",
    "Experience managing 40–60 accounts simultaneously in a high-touch model (not 300+ reactive CS)",
    "Direct ownership of revenue outcomes — renewal, expansion, or book-of-business revenue (CSAT-only experience is insufficient)",
    "Proactive, relationship-first communication style; reaches out before districts ask",
    "Strong written and verbal communication; proficiency in Google Suite",
    "Project management across multiple stakeholders and priorities",
    "Genuine commitment to serving under-resourced communities",
  ],
  niceToHave:[
    "Active clinical license in a Southeast state (LCSW, LICSW, LMHC, LCPC, PhD/PsyD)",
    "Familiarity with Multi-Tiered System of Support (MTSS) frameworks",
    "Experience with Salesforce, ChurnZero, or Asana",
    "Prior startup or early-stage company experience",
    "Experience with immigrant populations, rural communities, or military-connected families",
    "Curiosity about AI tools and how they apply to CS workflows",
  ],
  whatYoullDo:[
    {label:"Own Your Book of Business",bullets:[
      "Manage a portfolio of 40–60 school district accounts across the Southeast territory",
      "Establish proactive communication cadences with district contacts — Superintendents, Directors of Student Services, school staff",
      "Provide Cartwheel leadership with clean, timely account health updates — strengths, risks, and opportunities flagged before they escalate",
    ]},
    {label:"Drive Utilization and Strategic Alignment",bullets:[
      "Connect Cartwheel's utilization data to each district's published strategic plan in QBRs and ongoing conversations",
      "Build the ROI narrative that earns renewals and opens expansion conversations — not just reports numbers",
      "Identify accounts with low adoption, diagnose root causes, and pull the right levers to turn them around",
    ]},
    {label:"Support Growth and Renewals",bullets:[
      "Own the renewal pipeline across your territory — no surprise churns",
      "Partner with Account Managers on expansion opportunities and procurement cycles",
      "Recognize growth signals and position Cartwheel as a strategic partner, not a vendor",
    ]},
    {label:"Contribute Cross-Functionally",bullets:[
      "Feed district feedback to Product and Care teams consistently and with context",
      "Partner with Care Managers and Coordinators on in-school trends and student-level issues",
      "Navigate the Sales → Success handoff and help refine it as the team scales",
    ]},
  ],
  aboutRole:"Cartwheel is the largest mental health telehealth provider for K–12 schools in the U.S., serving 350+ school districts and 1.5M+ students — including some of the most under-resourced communities in the country. Our CS team is at the center of how that mission gets delivered at the district level.\n\nThis role will own Cartwheel's Southeast territory from day one — primarily East Coast and adjacent states — with a clear mandate: be the trusted advisor that district leadership calls when something goes wrong, and the strategic partner who makes the case for Cartwheel in every budget cycle.\n\nThis isn't a reactive CS role. There's no automation carrying your touchpoints and no SDR running the expansion play. You'll read district strategic plans, map our utilization data to district goals, flag account health before it becomes a problem, and help build what great CS looks like in K-12 mental health — because the playbook is still being written.",
  compBenefits:"Base salary: $95,000–$110,000 + 10% variable compensation. Cartwheel offers competitive benefits including health, dental, and vision coverage, generous PTO, and a remote-first work environment. This role includes occasional travel to Georgia and Southeast territory districts (approximately 10–15%).",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:[
      "Know your account model at a concrete level — be ready to describe how many accounts you've managed, how much revenue you've owned, and what your day-to-day engagement looked like",
      "Have a real example ready of owning a revenue outcome — a renewal you personally secured, an expansion you initiated, or a book-of-business metric you moved",
      "Be ready to speak specifically to your K-12 exposure — if you've worked in or adjacent to school systems, know what you learned about how districts make decisions",
      "Be honest about what draws you to mission-driven work — a specific moment or career decision that reflects your commitment to under-resourced communities will land better than a generic answer",
      "Know your comp expectations, geography, and timeline; the role includes flexible travel to districts as needed",
    ],questions:[
      "What does the account handoff from the current team look like for an incoming CSM?",
      "What does the onboarding timeline look like, and how much ramp time is built in before I'm expected to be independent on my accounts?",
      "What's the biggest challenge facing the CS team right now as the team transitions to a new management structure?",
    ]},
    {stage:"Hiring Manager Interview",prep:[
      "Prepare a specific book of business story — what you inherited, what you built, and what the numbers looked like at each stage; Jeanine will probe for specifics, not direction",
      "Think through a time an account was at risk and how you knew before anyone told you — what was the signal, and what did you do before it became a problem?",
      "Be ready to talk about a renewal or expansion you had to earn — who was the decision-maker, what did you do, and what would have happened if you hadn't acted?",
      "Be ready to articulate what you need from a manager to do your best work and what a strong CSM-to-manager relationship looks like to you",
    ],questions:[
      "What does the current account health look like across the book — are there accounts that are already at risk that I'd be inheriting?",
      "How does success get measured for this role at 6 and 12 months — and what does the reporting cadence to leadership look like?",
      "What's your vision for how the CS function evolves as Cartwheel scales to 1,000+ districts?",
    ]},
    {stage:"Functional Deep Dive",prep:[
      "This panel includes two CSMs — think peer-level calibration; they're evaluating whether you'd raise the bar on the team, not just meet it",
      "Prepare a specific utilization turnaround story — not 'I worked with the district to improve things' but what you actually did, what levers you pulled, who you needed buy-in from, and how long it took",
      "Be ready to build a QBR narrative out loud: the panelists may give you a scenario with utilization data and ask you to frame it for a district contact — have your thinking organized before you walk in",
      "Prepare a cross-functional navigation story with real tension — not a smooth collaboration, but a situation where priorities or ownership were unclear and you had to work through it",
      "Think about how you've contributed feedback to a product or operations team — what you surfaced, how you packaged it, and whether anything actually changed",
    ],questions:[
      "What does a strong QBR look like at Cartwheel right now — and where does the team feel like there's room to improve?",
      "How does the CS team currently collaborate with Account Managers on renewal conversations — who owns what?",
      "What's the most common reason a district's utilization stalls, and what's worked to turn it around?",
    ]},
    {stage:"Domain & Stakeholder Screen",prep:[
      "This stage evaluates how you operate at the district leadership level — have a specific story ready that names real dynamics with Superintendents or Directors of Student Services, not just 'great relationships'",
      "The clinical boundary question is intentional — be prepared to articulate where the line is between being a useful thought partner and overstepping; both overclaiming and underclaiming are red flags",
      "Think through a moment when you joined a role where the playbook wasn't written — what did you do first, what did you choose not to fix, and what's your honest assessment of how you performed?",
      "Have a relationship repair story ready — a moment when trust with a district stakeholder was damaged and how you rebuilt it; interviewers are looking for real friction, not universal positivity",
    ],questions:[
      "How does the CS team currently navigate conversations with district leaders who want clinical guidance that goes beyond the CSM's scope?",
      "What does the most successful CSM on the current team do that others don't?",
      "How does Cartwheel support CSMs who are navigating a particularly high-complexity district relationship?",
    ]},
    {stage:"Case Study Presentation",prep:[
      "You'll receive the take-home exercise before this session — read it carefully and prioritize your 60–90 minutes across all three parts; the exercise is designed to be completable in that window without perfectionism",
      "Part A (project plan): lead with your prioritization logic, not just a task list; explain what was obvious, what was hard, and what you'd add or cut and why",
      "Part B (data slides): your goal is to tell a story that drives action — make clear what the problem is, what the opportunity is, and what you're asking the district to do next",
      "Part C (email): deliver a difficult message with warmth and clarity — don't over-apologize, don't bury the key information, and don't give clinical detail that isn't appropriate in a written channel",
      "Jeanine and Sarah are evaluating whether you could walk into a Superintendent's office tomorrow and represent Cartwheel credibly — let your thinking be visible, not just your conclusions",
    ],questions:[
      "What does the Jingle Public Schools account look like today — is it a district type I'd be likely to encounter in my book?",
      "What does the typical relationship between a CSM and a Director of Student Services look like in Cartwheel's strongest district partnerships?",
      "What's the most common mistake CSMs make in their first QBR with a new district?",
    ]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:[
      "Review Cartwheel's website and understand the core product — mental health telehealth for K–12 schools",
      "Prepare your account model summary: how many accounts, how much revenue, what your engagement cadence looked like",
      "Have one concrete revenue outcome ready — a renewal, expansion, or retention metric you personally influenced",
      "Think through your K-12 exposure and what you learned about how districts operate",
      "Know your compensation expectations, availability, and target start date; confirm comfort with occasional district travel",
    ]},
    {stage:"Before Hiring Manager Interview",items:[
      "Research Jeanine Avjean on LinkedIn — understand her background and how she describes the CS function",
      "Prepare 2–3 specific stories: book-of-business ownership, at-risk account you caught proactively, renewal or expansion you earned",
      "Think through what you need from a manager to do your best work — this is a team in transition and Jeanine will want to understand your working style",
      "Prepare thoughtful questions about where the CS team is headed and how success is measured",
    ]},
    {stage:"Before Functional Deep Dive",items:[
      "Prepare your utilization turnaround story with specifics: what you did, who you needed, how long it took, what changed",
      "Practice building a QBR narrative out loud — what data points you'd lead with, how you'd connect them to a district's goals, how you'd frame an ask",
      "Have a cross-functional navigation story ready that involves real tension — not smooth collaboration",
      "Think through what feedback you've contributed to a product or operations team and what happened as a result",
    ]},
    {stage:"Before Domain Screen",items:[
      "Prepare a district stakeholder story with real complexity — competing priorities, named dynamics, specific moves you made",
      "Think through your clinical boundary position — where is the line between thought partner and overstepping?",
      "Prepare your ambiguity story: a role you joined where the playbook didn't exist and what you did first",
      "Have a relationship repair story ready — something went wrong with a district contact and you rebuilt trust",
    ]},
    {stage:"Before Case Study Presentation",items:[
      "Read the take-home exercise carefully and allocate your 60–90 minutes across all three parts before you start",
      "Part A: build a project plan that shows judgment about what matters, not exhaustiveness",
      "Part B: build slides that tell a story about Jingle Public Schools and drive a clear action — not a data report",
      "Part C: draft an email that is warm, direct, and clinical-boundary-appropriate — no over-apologizing, no buried key information",
      "Be ready to walk Jeanine and Sarah through your thinking, not just your output — they'll probe your trade-offs and assumptions",
    ]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Avery Henry",title:"Recruiter",href:"https://www.linkedin.com/in/averyhenry/"},
    {label:"Hiring Manager Interview",name:"Jeanine Avjean",title:"Sr. Manager of Customer Success",href:"https://linkedin.com/in/jeanine-avjean-1200a01a3/"},
    {label:"Functional Deep Dive",name:"",title:"",href:null,multiHrefs:[
      {name:"Customer Success Manager",href:null},
      {name:"Emily Boyce",href:"https://www.linkedin.com/in/emilyboyce/"},
    ]},
    {label:"Domain & Stakeholder Screen",name:"Suzy Hall",title:"Customer Success Enablement Manager",href:"https://www.linkedin.com/in/suzy-hall-a8b846101/"},
    {label:"Case Study Presentation",name:"",title:"",href:null,multiHrefs:[
      {name:"Jeanine Avjean",href:"https://linkedin.com/in/jeanine-avjean-1200a01a3/"},
      {name:"Sarah Shoff",href:"https://www.linkedin.com/in/sarah-shoff-she-her-1330a54/"},
    ]},
  ],
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const BUILT_IN_ROLES = [PDA_ROLE, CTRL_ROLE, GROM_ROLE, FPAA_ROLE, ROA_ROLE, CSM_ROLE];
