export const PDA_ROLE = {
  title:"Principal Data Analyst", slug:"principal-data-analyst",
  department:"Data", reportsto:"Jacob Savos, Director of Data",
  location:"Remote", employment:"Full-Time, W2", comp:"$170,000 - $210,000",
  mission:"Shape the analytics foundation that helps Cartwheel understand and improve how mental health care reaches students. Your work connects data decisions to real outcomes for kids.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:["Jacob Savos — Director of Data (your hiring manager)","1 Analytics Manager","1 Senior Data Analyst","1 Staff Data Engineer","You — senior IC thought partner to Jacob"],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Role fit, values, compensation"},
    {stage:"Hiring Manager",time:"30m",who:"Jacob Savos",focus:"Systems thinking, data modeling, strategic partnership"},
    {stage:"Take-Home Exercise",time:"60-90m",who:"",focus:"SQL proficiency + analytical proposal"},
    {stage:"Case Study Review",time:"60m",who:"Nicholas Franchetti",focus:"Take-home review, data integrity, dashboards"},
    {stage:"Business Acumen",time:"30m",who:"Sam Blumpkin + Sam Bilow",focus:"Structured reasoning, business scenarios"},
    {stage:"Exec Review",time:"30m",who:"Daniel Ilkovich, CTO",focus:"Final alignment"},
  ],
  contacts:["Recruiter: Caroline Colpini - caroline.colpini@cartwheelcare.org","Coordinator: Avery Henry - avery.henry@cartwheelcare.org","Take-home questions: Jacob Savos - jacob.savos@cartwheelcare.org"],
  prep:["Bring 1-2 examples of analytics systems you have owned end-to-end","Walk through context, approach, tradeoffs, validation, and impact","Think about how your work scales — we care about foundations, not one-off outputs","This is a conversation, not a performance"],
  thrive:["Think in systems and care about foundations, not just outputs","Take ownership from concept through durable implementation","Want to build something that outlasts your tenure","Care genuinely about student mental health impact"],
  notfor:["Need highly defined requirements before starting","Optimize locally without considering long-term maintainability","See governance and documentation as overhead","Prefer isolated work over cross-team partnership"],
  success:[
    {period:"First 90 Days",desc:"Audit data systems, ship one small improvement, build key relationships, and propose 2-3 architecture priorities."},
    {period:"First 6 Months",desc:"Core analytical models well-designed and trusted. Metrics defined consistently. Self-service analytics enabling Product, Clinical, and Ops teams."},
    {period:"First 12 Months",desc:"Analytics shifted from reactive reporting to proactive enablement. Executive team uses data confidently. Recognized as the Director of Data's key thought partner on strategy."},
  ],
  mustHave:["8+ years in analytics, data, or a related technical role","Advanced SQL proficiency with complex, messy datasets","Experience designing analytical data models and defining metrics at scale","Experience with BigQuery, Snowflake, or Redshift","Systems-thinking mindset","Ownership mentality: concept through durable implementation"],
  niceToHave:["Healthcare, mental health, or EdTech domain experience","Early-stage or high-growth startup experience","Experimentation or causal analysis tools (Python, R)","Analytics engineering tooling (dbt, data governance)"],
  whatYoullDo:[
    {label:"Data Architecture",bullets:["Design and evolve core analytical data models","Establish standards for metrics, transformations, and semantic layers","Define best practices for analytics quality and long-term maintainability","Partner with data engineering and product to ensure foundations scale"]},
    {label:"Technical Leadership",bullets:["Serve as senior thought partner to the Director of Data","Provide architectural guidance across the data team","Set the bar for what great analytics work looks like at Cartwheel","Support evolution from ad-hoc analysis to productized solutions"]},
    {label:"Enablement",bullets:["Build and support self-service analytics and executive-ready reporting","Ensure new launches are instrumented with clear success metrics from Day 1","Improve measurement of outcomes: access to care, conversion, retention","Support experimentation across R&D, Marketing, and Operations"]},
    {label:"Governance",bullets:["Champion data quality through testing, monitoring, and governance","Ensure analytical workflows are reproducible, well-documented, and resilient","Contribute to data dictionaries, metric definitions, and shared documentation"]},
  ],
  aboutRole:"The Principal Data Analyst is a senior individual contributor responsible for shaping the analytics and data foundation at Cartwheel. This role emphasizes data system design, analytical architecture, and defining best practices for how data is modeled and delivered.\n\nYou will work as a staff-level technical leader on the data team — a close thought partner to the Director of Data — helping raise the bar for what good analytical work looks like.",
  compBenefits:"$170,000-$210,000 cash compensation plus competitive equity. Full benefits: PPO medical/vision/dental/orthodontia, paid parental leave (12 weeks), 401K with 2% employer match, generous PTO including Dec 25-Jan 1 closure, $500 learning stipend, MacBook, and annual in-person retreat.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:["Research Cartwheel's mission and school-based model","Prepare a concise background summary focused on data leadership","Know your comp expectations within the $170K-$210K range","Think about what draws you to mission-driven work"],questions:["What does success look like in the first 90 days?","How does the data team collaborate with Product and Clinical?","What is the biggest data challenge Cartwheel is working through?"]},
    {stage:"Hiring Manager",prep:["Prepare 1-2 analytics framework examples with full context","Walk through context, approach, tradeoffs, validation, and impact","This is not a deep technical test — clarity of thinking matters most","Think about how you have moved teams from ad-hoc to productized solutions"],questions:["What are the 2-3 most important things to accomplish in year one?","How do you see the analytics team evolving over the next 12-18 months?","What does great thought partnership look like day-to-day?"]},
    {stage:"Take-Home Exercise",prep:["Block 90 uninterrupted minutes — treat it like a real work session","Read all questions before starting so you can manage your time","Write clean SQL with comments to show your thinking","Lead the proposal with the metrics that matter most, and explain your reasoning"],questions:[]},
    {stage:"Case Study Review",prep:["Prepare a tight 3-minute take-home recap: problem, scope, approach","Walk through your SQL — be ready to discuss efficiency and alternatives","Be honest about gaps or assumptions — strong candidates own them","Think through what a Day 1 dashboard for a new service line would look like"],questions:["What does the current data quality monitoring process look like?","How does the team handle discrepancies between data sources?","What does the analytics tooling stack look like end-to-end?"]},
    {stage:"Business Acumen",prep:["Practice walking through a problem out loud — narrate your thinking","Prepare to ask clarifying questions before jumping to answers","Propose next steps and recommendations, not just diagnoses","This is collaborative, not adversarial — think of it as a working session"],questions:["What business problems is the data team most focused on?","How does data inform go-to-market or expansion decisions?","What does the relationship between data and clinical look like?"]},
    {stage:"Exec Review",prep:["Prepare your long-term vision for data at a company like Cartwheel","Have a thoughtful answer for where you want to be in 3 years","Know why Cartwheel specifically — mission alignment will come up","Prepare 2-3 questions that show strategic thinking"],questions:["How does the exec team use data today, and how would you like that to evolve?","What is Cartwheel's biggest strategic bet over the next 2 years?","How does data infrastructure factor into the growth roadmap?"]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:["Research Cartwheel's mission and school-based model","Prepare your background summary","Know your comp expectations","Review the job description"]},
    {stage:"Before HM Interview",items:["Prepare 2 analytics framework examples","Practice walking through tradeoffs out loud","Review Cartwheel's clinical model","Prepare 3-4 thoughtful questions for Jacob"]},
    {stage:"Before Take-Home",items:["Block 90 uninterrupted minutes","Re-read all questions before starting","Prepare a clean memo or slide deck template","Plan to submit within one week"]},
    {stage:"Before Case Study Review",items:["Prepare a 3-min take-home recap","Review your SQL for efficiency improvements","Think through your data integrity approach","Prepare dashboard design thinking"]},
    {stage:"Before Business Acumen",items:["Practice metric decomposition out loud","Prepare to ask clarifying questions","Review Cartwheel's business model","Think about how data enables go-to-market decisions"]},
    {stage:"Before Exec Review",items:["Prepare your long-term vision for data at Cartwheel","Sharpen your why Cartwheel answer","Prepare 2-3 strategic questions for Daniel","Reflect on what excites you most about the mission"]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Hiring Manager",name:"Jacob Savos",title:"Director of Data",href:"https://www.linkedin.com/in/jacob-savos/"},
    {label:"Take-Home Exercise",name:"",title:"",href:null},
    {label:"Case Study Review",name:"Nicholas Franchetti",title:"",href:"https://www.linkedin.com/in/nfranchetti/"},
    {label:"Business Acumen",name:"Sam Blumpkin + Sam Bilow",title:"",href:null,hrefs:["https://www.linkedin.com/in/samblumkin/","https://www.linkedin.com/in/sam-bilow-59434150/"]},
    {label:"Exec Review",name:"Daniel Ilkovich",title:"CTO",href:"https://www.linkedin.com/in/ilkovich/"},
  ],
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const SPM_ROLE = {
  title:"Senior Product Manager, AI Products", slug:"senior-product-manager-ai",
  department:"R&D", reportsto:"Sarah Turrin, Chief Product Officer",
  location:"Boston or Chicago preferred, Remote-friendly", employment:"Full-Time, W2", comp:"$120,000 - $170,000",
  mission:"Build the AI-enabled tools that transform how schools and clinicians deliver mental health care — turning messy, real-world workflows into software that actually works for the people using it.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:["Sarah Turrin — CPO (your hiring manager)","Product Design (workflow design, prototyping)","Engineering (system behaviors, edge cases, scalability)","School staff and end users (direct user research)","Executive leadership (product direction and tradeoffs)"],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Role fit, values, compensation"},
    {stage:"Product Judgment",time:"60m",who:"Sarah Turrin, CPO",focus:"Ambiguous problem-solving, 0-to-1 ownership, AI product perspective"},
    {stage:"Technical Design",time:"60m",who:"Danielle Hawthorne, Henry Lyford, Sandip Subedi",focus:"Workflow translation, cross-functional tradeoffs, AI trust and safety"},
    {stage:"User-Centered Discovery",time:"60m",who:"Julie Jungman, Allie Pashi, Sarah Shoff, GG Guitart, Rebecca Rae Allen",focus:"User research approach, synthesizing feedback, building trust with users"},
    {stage:"Live Product Case",time:"60m",who:"Sarah Turrin, Daniel Ilkovich, Dan Tartakovsky, Sam Bilow",focus:"Problem framing, MVP definition, structured reasoning under ambiguity"},
    {stage:"Executive Review",time:"30m",who:"Joe English, CEO",focus:"Mission alignment, growth mindset, long-term values fit"},
  ],
  contacts:["Recruiter: Caroline Colpini - caroline.colpini@cartwheelcare.org","Coordinator: Avery Henry - avery.henry@cartwheelcare.org"],
  prep:["Bring 1-2 examples of products you have personally owned end-to-end","Focus on how you think, not just what shipped — tradeoffs, decisions, learnings","Be honest about the limits of AI in your work — we value that perspective","This is a working session, not a test"],
  thrive:["Enjoy ambiguity and shaping problems from scratch","Are comfortable balancing speed, quality, and scalability","Like spending time with real users in real environments","Build and use AI tools as part of your everyday workflow"],
  notfor:["Require highly defined requirements or rigid processes","Avoid direct customer interaction or rely on secondhand insights","Add heavyweight process instead of enabling fast learning","Over-index on strategy decks without shipping or validating quickly"],
  success:[
    {period:"First 90 Days",desc:"Deeply understand school and care team workflows; conduct in-person user research; define problem statements and MVP scopes; ship at least one validated prototype."},
    {period:"First 6 Months",desc:"Launch initial AI-enabled product capability with active customer usage; establish clear success metrics; iterate based on qualitative and quantitative feedback."},
    {period:"First 12 Months",desc:"Own a portfolio of 0-to-1 initiatives with sustained adoption; demonstrate measurable workflow efficiency gains; help establish lightweight product practices across the org."},
  ],
  mustHave:["7+ years of Product Management experience with clear 0-to-1 ownership","Demonstrated experience building or prototyping AI-enabled products","Comfort with workflow-heavy, operational tools (healthcare, education, GovTech)","Strong product judgment under ambiguity and incomplete data","Proven ability to work directly with customers and conduct user research","Ability to operate as a senior IC who influences direction"],
  niceToHave:["Experience with AI-native patterns (copilots, workflow automation, decision support)","Background in regulated domains (healthcare, education)","Familiarity with low-code or no-code tools","Experience building internal tools that later became customer-facing","Startup or early-stage company experience"],
  whatYoullDo:[
    {label:"0-to-1 AI Product Development",bullets:["Lead development of new AI-enabled SaaS tools from early concept through initial adoption","Partner with Design and Engineering to shape workflows, MVPs, and system behaviors","Use AI prototyping tools to accelerate discovery, experimentation, and iteration","Make pragmatic tradeoffs between speed, quality, and scalability"]},
    {label:"Workflow Translation",bullets:["Spend time directly with school staff to understand real-world workflows","Translate messy, real-world problems into clear product abstractions","Design products focused on workflow automation and decision-support","Build products that balance speed with safety, trust, and usability"]},
    {label:"Discovery and Iteration",bullets:["Define success metrics and use qualitative and quantitative feedback to guide iteration","Conduct sustained, in-person user research with school staff and care teams","Navigate conflicting signals between what users say vs. do","Know when you have learned enough to move forward"]},
    {label:"Org Contribution",bullets:["Help establish lightweight product practices that enable fast learning","Collaborate with GTM teams on marketing and how product lands in market","Operate as a senior IC who shapes direction and raises the bar"]},
  ],
  aboutRole:"Cartwheel is building technology that supports how mental health care is delivered and coordinated in school settings. We are looking for a Senior Product Manager, AI Products to lead early-stage product initiatives focused on improving how complex work gets done.\n\nThis is a senior individual contributor role for someone who thrives in ambiguity, partners closely with customers, and enjoys shaping products from the earliest stages.",
  compBenefits:"$120,000-$170,000 base compensation plus meaningful equity. Level and comp may flex for exceptional candidates. Full benefits: PPO medical/vision/dental, paid parental leave, 401K with employer match, generous PTO, $500 learning stipend, MacBook, and annual in-person retreat.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:["Research Cartwheel's mission and school-based model","Prepare your background summary focused on 0-to-1 product work","Know your comp expectations within the $120K-$170K range","Think about why AI and mental health and education draws you in"],questions:["What does success look like in the first 90 days?","How does the PM team collaborate with Engineering and Design?","What AI initiatives is Cartwheel most focused on right now?"]},
    {stage:"Product Judgment",prep:["Prepare 1-2 examples of products you have personally owned end-to-end","Focus on how you think, not just what shipped","Be ready to discuss your honest perspective on AI's real-world usefulness and limits","Think out loud, ask questions, collaborate — this is a working session"],questions:["What is the most important problem to solve in year one?","How does Cartwheel think about AI safety and trust in product?","What does the product development process look like today?"]},
    {stage:"Technical Design",prep:["Prepare examples of how you have handled cross-functional tension","Practice translating a messy workflow into a product concept out loud","Think through how you would handle an AI edge case involving student data","There may be a lightweight live exercise — focus on clarity over perfection"],questions:["How do Engineering and Design collaborate on early-stage initiatives?","What is the biggest technical constraint on AI product development right now?","How do you handle edge cases in workflows involving sensitive student data?"]},
    {stage:"User-Centered Discovery",prep:["Prepare 2 examples where user research changed your direction","Think through your approach to building trust with overwhelmed users","Review Cartwheel's school and clinical user types","Prepare questions about the current user research process"],questions:["How do school staff currently experience the Cartwheel product?","What is the hardest user research challenge in school-based mental health?","How do care teams and school staff interact differently with the product?"]},
    {stage:"Live Product Case",prep:["No slides needed — practice structured thinking out loud","Focus on framing the problem, identifying constraints, defining a reasonable MVP","Practice staying calm and collaborative when working through ambiguity","Prepare 1-2 clarifying questions to ask before diving in"],questions:["What is the most important constraint I should keep in mind?","How would you want this type of thinking applied on the job?"]},
    {stage:"Executive Review",prep:["Prepare your why Cartwheel answer — mission alignment will be central","Have a thoughtful answer for how you reflect on mistakes and growth","Prepare 2-3 strategic questions about where Cartwheel is headed","This is a two-way conversation — Joe expects you to interview him too"],questions:["What is the biggest strategic bet Cartwheel is making over the next 2 years?","How do you think about AI's role in Cartwheel's long-term competitive position?","What does the culture look like as the company scales past 200 people?"]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:["Research Cartwheel's mission and school-based model","Prepare your background summary","Know your comp expectations","Review the job description"]},
    {stage:"Before Product Judgment Round",items:["Prepare 2 end-to-end product examples","Articulate the tradeoffs you made and what you learned","Prepare your honest perspective on AI's real-world usefulness","Review Cartwheel's product and clinical model"]},
    {stage:"Before Technical Design Round",items:["Prepare cross-functional collaboration examples","Practice translating a messy workflow into a product concept out loud","Think through how you would handle an AI edge case involving student data","Prepare for a possible lightweight live exercise"]},
    {stage:"Before User-Centered Discovery",items:["Prepare 2 examples where user research changed your direction","Think through your approach to building trust with overwhelmed users","Review Cartwheel's school and clinical user types","Prepare questions about the current user research process"]},
    {stage:"Before Live Product Case",items:["No slides needed — practice structured thinking out loud","Review basic product framing: problem, constraints, MVP, metrics","Practice staying calm and collaborative under ambiguity","Prepare 1-2 clarifying questions to ask before diving in"]},
    {stage:"Before Executive Review",items:["Sharpen your why Cartwheel answer","Prepare how you reflect on a past mistake and what you learned","Prepare 2-3 strategic questions for Joe","Reflect on your long-term motivations and values alignment"]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Product Judgment",name:"Sarah Turrin",title:"CPO",href:"https://www.linkedin.com/in/sarahturrin/"},
    {label:"Technical Design",name:"",title:"",href:null,multiHrefs:[
      {name:"Danielle Hawthorne",href:"https://www.linkedin.com/in/daniellemhawthorne/"},
      {name:"Henry Lyford",href:"https://www.linkedin.com/in/hlyford/"},
      {name:"Sandip Subedi",href:"https://www.linkedin.com/in/sandipsubedi/"},
    ]},
    {label:"User-Centered Discovery",name:"",title:"",href:null,multiHrefs:[
      {name:"Julie Jungman",href:"https://www.linkedin.com/in/julie-jungman-lcsw/"},
      {name:"Allie Pashi",href:"https://www.linkedin.com/in/allie-pashi/"},
      {name:"Sarah Shoff",href:"https://www.linkedin.com/in/sarah-shoff-she-her-1330a54/"},
      {name:"GG Guitart",href:"https://www.linkedin.com/in/gg-guitart/"},
      {name:"Rebecca Rae Allen",href:"https://www.linkedin.com/in/rebecca-rae-allen/"},
    ]},
    {label:"Live Product Case",name:"",title:"",href:null,multiHrefs:[
      {name:"Sarah Turrin",href:"https://www.linkedin.com/in/sarahturrin/"},
      {name:"Daniel Ilkovich",href:"https://www.linkedin.com/in/ilkovich/"},
      {name:"Dan Tartakovsky",href:"https://www.linkedin.com/in/tartakovsky/"},
      {name:"Sam Bilow",href:"https://www.linkedin.com/in/sam-bilow-59434150/"},
    ]},
    {label:"Executive Review",name:"Joe English",title:"CEO",href:"https://www.linkedin.com/in/joe-m-english/"},
  ],
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const CCM_ROLE = {
  title:"Care Coordination Manager", slug:"care-coord-manager",
  department:"Operations", reportsto:"Allie Pashi, Director of Care Operations",
  location:"Remote with in-person team retreats in Boston", employment:"Full-Time, W2", comp:"$85,000 - $110,000",
  mission:"Own the operational excellence of Cartwheel's care coordination function — the front door for families navigating mental health support for their children.",
  stats:[{n:"350+",label:"School Districts",sub:"Serving 2.5% of U.S. districts"},{n:"$20M",label:"in ARR",sub:"Achieved in just 3 years"},{n:"300%",label:"YoY Growth",sub:"Capital-efficient scale"},{n:"1.5M",label:"Students",sub:"Enrolled across districts"}],
  team:["Allie Pashi — Director of Care Operations (hiring manager)","1 Care Coordinator Lead (manages 8-12 CCs)","Cross-functional: Provider Success, Clinical, School Success, Product (CCA Pod), Quality"],
  stages:[
    {stage:"Recruiter Screen",time:"30m",who:"Caroline Colpini",focus:"Role fit, values, compensation"},
    {stage:"Hiring Manager Deep Dive",time:"45m",who:"Allie Pashi",focus:"Operational discipline, data-driven decisions, accountability"},
    {stage:"Take-Home Exercise",time:"60-90m",who:"",focus:"Operational prioritization, SLA design, data interpretation"},
    {stage:"Cross-Functional Interview",time:"30m",who:"Jeanine Avjean + Jessi Dwyer",focus:"People leadership, collaboration, mission"},
    {stage:"Systems & Infrastructure Deep Dive",time:"30m",who:"Julie Jungman",focus:"Systems thinking, process design, automation"},
    {stage:"Exec Review",time:"30m",who:"Dan Tartakovsky, COO",focus:"Strategic thinking, growth potential, culture fit"},
  ],
  contacts:["Recruiter: Caroline Colpini - caroline.colpini@cartwheelcare.org","Coordinator: Avery Henry - avery.henry@cartwheelcare.org"],
  prep:["Bring 1-2 examples of operational systems you have built or improved end-to-end","Walk through context, decisions, tradeoffs, and measurable outcomes","Think about how you lead teams through ambiguity and hold standards without micromanaging","Demonstrate data literacy — be ready to talk through metrics and how you use them to drive decisions"],
  thrive:["Care deeply about the families and children this work serves","Love operational precision and find energy in building systems that scale","Are naturally data-driven and use metrics to drive decisions and accountability","Thrive as a people leader who develops team members and removes blockers"],
  notfor:["Prefer strategy over day-to-day operational ownership","Are uncomfortable with close metrics management and SLA accountability","Prefer working independently rather than deeply cross-functionally","Need highly structured processes before taking initiative"],
  success:[
    {period:"First 90 Days",desc:"Deeply understand the care coordination workflow end-to-end; build relationships across clinical, school, and product teams; audit current SLAs and identify top 2-3 operational improvements."},
    {period:"First 6 Months",desc:"Own care coordination metrics and throughput with clear accountability. Implement one or more process improvements that measurably reduce lag or improve family experience. Build trust with cross-functional stakeholders."},
    {period:"First 12 Months",desc:"Care coordination function runs with operational excellence — predictable SLAs, strong team performance, and reliable data. Recognized as a key partner across Provider Success, Clinical, and School Success."},
  ],
  mustHave:["3+ years managing care coordination, patient navigation, or operations in healthcare or social services","Experience setting and hitting SLAs in a high-volume, people-centered environment","Strong data literacy — comfortable building and using dashboards to drive decisions","Proven people leadership: developing direct reports and holding teams accountable","Ability to collaborate across clinical, operational, and technical teams"],
  niceToHave:["Experience in school-based mental health, pediatric healthcare, or EdTech","Familiarity with care management platforms or EHR workflows","Process automation or workflow optimization experience","Startup or high-growth company experience"],
  whatYoullDo:[
    {label:"Operational Excellence",bullets:["Own the end-to-end care coordination workflow from first family contact through care match","Set, monitor, and improve SLAs across the care coordination function","Identify and remove operational bottlenecks that slow families down","Build processes that scale with Cartwheel's growth without sacrificing quality"]},
    {label:"People Leadership",bullets:["Directly manage and develop a Care Coordinator Lead who oversees 8-12 Care Coordinators","Build a culture of accountability, compassion, and continuous improvement","Support hiring, onboarding, and performance management for the CC team","Coach team members through complex family situations and escalations"]},
    {label:"Data and Metrics",bullets:["Define and track operational KPIs across the care coordination function","Use data to surface trends, identify risks, and prioritize improvements","Report care coordination performance to Allie and cross-functional leadership","Collaborate with Product to improve tooling and surface data-driven insights"]},
    {label:"Cross-Functional Partnership",bullets:["Partner with Provider Success to ensure smooth provider matching and onboarding","Collaborate with Clinical to align care coordination workflows with clinical standards","Work with School Success to understand district-specific needs and feedback","Engage with Product (CCA Pod) to shape tooling that improves coordinator efficiency"]},
  ],
  aboutRole:"The Care Coordination Manager owns the operational excellence of Cartwheel's care coordination function — the front door for families navigating mental health support for their children. This role is central to Cartwheel's mission: ensuring every family who reaches out gets a thoughtful, timely, and high-quality experience.\n\nYou will lead a team of Care Coordinators through a dedicated Lead, set and hold SLAs, and partner deeply with Clinical, Provider Success, School Success, and Product to continuously improve how families access care.",
  compBenefits:"$85,000-$110,000 base compensation plus meaningful equity. Full benefits: PPO medical/vision/dental, paid parental leave, 401K with employer match, generous PTO including Dec 25-Jan 1 closure, $500 learning stipend, MacBook, and annual in-person retreat in Boston.",
  stagePrepData:[
    {stage:"Recruiter Screen",prep:["Research Cartwheel's mission, school-based model, and care coordination approach","Prepare a concise background summary focused on operational leadership","Know your comp expectations within the $85K-$110K range","Think about what draws you to care coordination and mental health access work"],questions:["What does success look like in the first 90 days?","What are the biggest operational challenges in care coordination today?","How does the care coordination team interact with clinical and school teams?"]},
    {stage:"Hiring Manager Deep Dive",prep:["Prepare 1-2 examples of operational systems or workflows you have built or improved","Walk through a situation where you held your team to a high standard under pressure","Be ready to talk about how you use data to drive decisions and accountability","Think about a time you improved a process that meaningfully changed the family or user experience"],questions:["What are the top 1-2 operational priorities for care coordination right now?","How does Allie think about the right pace of growth for the team?","What does great operational partnership between care coordination and clinical look like?"]},
    {stage:"Take-Home Exercise",prep:["Block 60-90 uninterrupted minutes — treat it like a real work session","Read all prompts before starting to manage your time well","Lead with your reasoning, not just your answers — show how you think through tradeoffs","Use concrete frameworks for prioritization and SLA design"],questions:[]},
    {stage:"Cross-Functional Interview",prep:["Prepare 2 examples of cross-functional collaboration that required trust-building","Think through how you lead through influence rather than authority","Reflect on a time you advocated for your team's needs with other departments","Be ready to share what mission-driven work means to you personally"],questions:["How do Care Coordinators interact with school staff and families day-to-day?","What does the relationship between Care Coordination and School Success look like in practice?","How is collaboration structured across the CCA Pod?"]},
    {stage:"Systems & Infrastructure Deep Dive",prep:["Prepare examples of process design, automation, or tooling improvements you have led","Think through how you approach building systems that are both rigorous and human","Be ready to discuss a workflow you mapped, improved, and measured","Reflect on how you balance automation with the need for human judgment"],questions:["What systems or tools does the care coordination team use today?","What process improvements would have the most impact in the next 6 months?","How does Julie think about the intersection of clinical quality and operational efficiency?"]},
    {stage:"Exec Review",prep:["Prepare your why Cartwheel answer — mission alignment will be central","Think about how operational excellence translates to strategic growth","Prepare 2-3 thoughtful questions about Cartwheel's next chapter","Have a clear perspective on how care coordination contributes to Cartwheel's competitive position"],questions:["What is Cartwheel's biggest operational challenge as it scales?","How does Dan think about the relationship between operational rigor and company culture?","What does growth look like for the care coordination function over the next 2 years?"]},
  ],
  checklist:[
    {stage:"Before Recruiter Screen",items:["Research Cartwheel's mission and school-based model","Prepare your background summary","Know your comp expectations","Review the job description"]},
    {stage:"Before Hiring Manager Deep Dive",items:["Prepare 2 operational leadership examples with outcomes","Walk through how you use data to drive decisions","Prepare 3-4 thoughtful questions for Allie","Think about your approach to building accountable teams"]},
    {stage:"Before Take-Home Exercise",items:["Block 60-90 uninterrupted minutes","Re-read all prompts before starting","Focus on reasoning, tradeoffs, and measurable outcomes","Prepare to explain your SLA design logic clearly"]},
    {stage:"Before Cross-Functional Interview",items:["Prepare 2 cross-functional collaboration examples","Think through how you lead through influence","Reflect on what mission-driven work means to you","Prepare questions about the CCA Pod and how teams collaborate"]},
    {stage:"Before Systems & Infrastructure Deep Dive",items:["Prepare process design and automation examples","Think through a workflow you improved end-to-end","Reflect on how you balance rigor with human judgment","Prepare questions about the current tooling stack"]},
    {stage:"Before Exec Review",items:["Sharpen your why Cartwheel answer","Prepare your view on operational excellence and strategic growth","Prepare 2-3 strategic questions for Dan","Reflect on what excites you most about the mission"]},
  ],
  interviewers:[
    {label:"Recruiter Screen",name:"Caroline Colpini",title:"Talent Acquisition",href:"https://www.linkedin.com/in/caroline-colpini-154b27b4/"},
    {label:"Hiring Manager Deep Dive",name:"Allie Pashi",title:"Director of Care Operations",href:"https://www.linkedin.com/in/allie-pashi/"},
    {label:"Take-Home Exercise",name:"",title:"",href:null},
    {label:"Cross-Functional Interview",name:"",title:"",href:null,multiHrefs:[
      {name:"Jeanine Avjean",href:"https://www.linkedin.com/in/jeanine-avjean-1200a01a3/"},
      {name:"Jessi Dwyer",href:"https://www.linkedin.com/in/jessi-d-571b59100/"},
    ]},
    {label:"Systems & Infrastructure Deep Dive",name:"Julie Jungman",title:"VP of Clinical",href:"https://www.linkedin.com/in/julie-jungman-lcsw/"},
    {label:"Exec Review",name:"Dan Tartakovsky",title:"COO",href:"https://www.linkedin.com/in/tartakovsky/"},
  ],
  links:{cartwheel:"https://www.cartwheel.org",wallOfLove:"https://www.cartwheel.org/wall-of-love",glassdoor:"https://www.glassdoor.com/Overview/Working-at-Cartwheel-MA-EI_IE9563214.11,23.htm",linkedin:"https://www.linkedin.com/company/cartwheelcare/posts/?feedView=all"},
};

export const BUILT_IN_ROLES = [PDA_ROLE, SPM_ROLE, CCM_ROLE];
